"""Export capture.yaml as a TI mmWave Studio Lua template.

WARNING: Generated templates are NOT hardware-validated.
They must be reviewed before use on real hardware.
"""

from __future__ import annotations

from pathlib import Path

from awr2944_dca.config.schema import RadarConfig

_WARNING_BANNER = """\
--------------------------------------------------------------------------------
-- WARNING: Generated template only. Not hardware validated. Review before use.
-- Generated by awr2944_dca from: {source}
--
-- This file is a TEMPLATE based on our capture.yaml config.
-- Parameter positions in ar1.*() calls are based on reverse-engineering
-- DataCaptureDemo_xWR.lua and may not be correct for all firmware versions.
--
-- DO NOT run this on hardware without reviewing every parameter.
--------------------------------------------------------------------------------
"""


def export_lua_template(
    cfg: RadarConfig,
    output_path: str | Path,
    *,
    source_name: str = "capture.yaml",
) -> Path:
    """Generate a Lua template file from a RadarConfig.

    Returns the path to the generated file.
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Build TX/RX channel enable bitmasks
    tx_mask = 0
    for tx in cfg.hardware.tx_enabled:
        tx_mask |= (1 << tx)
    rx_mask = 0
    for rx in cfg.hardware.rx_enabled:
        rx_mask |= (1 << rx)

    # ADC format: 0=real, 1=complex1x, 2=complex2x
    adc_fmt = 1 if cfg.adc.is_complex else 0

    # ADC bits enum: 0=12, 1=14, 2=16
    bits_enum = {12: 0, 14: 1, 16: 2}.get(cfg.adc.bits, 2)

    lines = [
        _WARNING_BANNER.format(source=source_name),
        "",
        "-- ADC data output path",
        '-- TODO: Update this path to your actual capture directory',
        f'adc_data_path = "C:\\\\ti\\\\mmwave_studio\\\\PostProc\\\\adc_data.bin"',
        "",
        "-- TODO: Download BSS and MSS firmware (device-specific)",
        "-- ar1.DownloadBSSFw(BSS_FW)",
        "-- ar1.DownloadMSSFw(MSS_FW)",
        "-- RSTD.Sleep(100)",
        "",
        "-- TODO: Power on and RF enable",
        "-- ar1.PowerOn(1, 1000, 0, 0)",
        "-- ar1.RfEnable()",
        "-- RSTD.Sleep(100)",
        "",
        "-- Channel and ADC Configuration",
        f"-- TX enable mask: {tx_mask} ({cfg.hardware.tx_enabled})",
        f"-- RX enable mask: {rx_mask} ({cfg.hardware.rx_enabled})",
        f"-- ADC bits enum: {bits_enum} ({cfg.adc.bits}-bit)",
        f"-- ADC format: {adc_fmt} ({'complex' if cfg.adc.is_complex else 'real'})",
        f"-- IQ swap: 0",
        f"-- Channel interleave: {cfg.adc.channel_interleave}",
        f"ar1.ChanNAdcConfig({tx_mask}, {rx_mask}, 0, {bits_enum}, {adc_fmt}, 0, {cfg.adc.channel_interleave}, 2, 1, 0)",
        "RSTD.Sleep(100)",
        "",
        "-- Low Power Mode (regular mode)",
        "ar1.LPModConfig(0, 0)",
        "RSTD.Sleep(100)",
        "",
        "-- RF Init",
        "ar1.RfInit()",
        "RSTD.Sleep(1000)",
        "",
        "-- Data Path Configuration",
        "-- TODO: Verify intfSel parameter for your device",
        "ar1.DataPathConfig(1, 1, 0)",
        "RSTD.Sleep(100)",
        "",
        "-- LVDS Clock Configuration",
        "ar1.LvdsClkConfig(1, 1)",
        "RSTD.Sleep(100)",
        "",
        "-- LVDS Lane Configuration",
        "-- TODO: Verify lane enable mask for AWR2944 (2-lane)",
        "ar1.LVDSLaneConfig(0, 1, 1, 1, 1, 1, 0, 0)",
        "RSTD.Sleep(100)",
        "",
        "-- Profile Configuration",
        f"-- Start freq: {cfg.profile.start_freq_ghz} GHz",
        f"-- Idle time: {cfg.profile.idle_time_us} us",
        f"-- Ramp end time: {cfg.profile.ramp_end_time_us} us",
        f"-- Slope: {cfg.profile.slope_mhz_per_us} MHz/us",
        f"-- Samples: {cfg.adc.samples_per_chirp}",
        f"-- Sample rate: {cfg.profile.sample_rate_ksps} ksps",
        (
            f"ar1.ProfileConfig(0, {cfg.profile.start_freq_ghz}, "
            f"{cfg.profile.idle_time_us}, 6, "
            f"{cfg.profile.ramp_end_time_us}, "
            f"0, 0, 0, 0, 0, 0, "
            f"{cfg.profile.slope_mhz_per_us}, 0, "
            f"{cfg.adc.samples_per_chirp}, {cfg.profile.sample_rate_ksps}, "
            f"0, 0, 94)"
        ),
        "RSTD.Sleep(100)",
        "",
        "-- Chirp Configuration",
        "-- TODO: Verify chirp parameters for your setup",
        "ar1.ChirpConfig(0, 0, 0, 0, 0, 0, 0, 1, 1, 0)",
        "RSTD.Sleep(100)",
        "",
        "-- Frame Configuration",
        f"-- Chirps per frame: {cfg.frame.chirps_per_frame}",
        f"-- Num frames: {cfg.frame.num_frames}",
        f"-- Frame period: {cfg.frame.frame_period_ms} ms",
        "-- TODO: Verify framePeriodicity units (may need conversion)",
        (
            f"ar1.FrameConfig(0, 0, {cfg.frame.chirps_per_frame}, "
            f"{cfg.frame.num_frames}, "
            f"{cfg.frame.frame_period_ms}, 0, 1)"
        ),
        "RSTD.Sleep(100)",
        "",
        "-- DCA1000 Capture Card Setup",
        'ar1.SelectCaptureDevice("DCA1000")',
        'ar1.CaptureCardConfig_EthInit("192.168.33.30", "192.168.33.180", "12:34:56:78:90:12", 4096, 4098)',
        "ar1.CaptureCardConfig_Mode(1, 1, 1, 2, 3, 30)",
        f"ar1.CaptureCardConfig_PacketDelay({cfg.capture.packet_delay_us})",
        "",
        "-- Start Capture",
        "ar1.CaptureCardConfig_StartRecord(adc_data_path, 1)",
        "RSTD.Sleep(2000)",
        "",
        "-- Trigger Frame",
        "ar1.StartFrame()",
        "RSTD.Sleep(5000)",
        "",
        "-- Post Processing",
        "ar1.StartMatlabPostProc(adc_data_path)",
        'WriteToLog("Capture complete. Run post-processing.\\n", "green")',
        "RSTD.Sleep(10000)",
        "",
    ]

    output_path.write_text("\n".join(lines), encoding="utf-8")
    return output_path
