"""Export capture.yaml as a DCA1000 JSON configuration.

Fails clearly if required fields are missing.
Does NOT generate fake-complete JSON.
"""

from __future__ import annotations

import json
from pathlib import Path

from awr2944_dca.config.schema import RadarConfig


class DcaConfigError(Exception):
    """Raised when required fields are missing for DCA1000 config export."""

    pass


def export_dca_config(
    cfg: RadarConfig,
    output_path: str | Path,
) -> Path:
    """Generate a DCA1000 CLI JSON config from a RadarConfig.

    The DCA1000 CLI config format is based on TI DCA1000EVM CLI Software
    Developer Guide. Fields that cannot be determined from capture.yaml
    will cause a clear error.

    Returns the path to the generated file.
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Validate required fields
    errors: list[str] = []

    if cfg.capture.packet_delay_us <= 0:
        errors.append("capture.packet_delay_us must be > 0")

    # Determine data format mode
    # DCA1000 dataLoggingMode: 1=raw, 2=multi
    # DCA1000 dataCaptureMode: 1=Ethernet streaming, 2=SD card
    # DCA1000 dataTransferMode: 1=LVDS capture, 2=DMM

    if cfg.adc.num_lvds_lanes not in (2, 4):
        errors.append(
            f"num_lvds_lanes={cfg.adc.num_lvds_lanes} is not supported by DCA1000 (2 or 4)"
        )

    if errors:
        raise DcaConfigError(
            "Cannot generate DCA1000 config — missing/invalid fields:\n"
            + "\n".join(f"  - {e}" for e in errors)
        )

    dca_config = {
        "_comment": (
            "Generated by awr2944_dca. Review before use. "
            "Based on DCA1000 CLI Software Developer Guide."
        ),
        "_firmware_note": (
            "This config targets DCA1000 CLI v2.x. "
            "If your DCA1000 firmware version differs, the schema may not match."
        ),
        "DCA1000Config": {
            "dataLoggingMode": "raw",
            "dataTransferMode": "LVDSCapture",
            "dataCaptureMode": "ethernetStream",
            "lvdsMode": cfg.adc.num_lvds_lanes,
            "dataFormatMode": 3 if not cfg.adc.is_complex else 1,
            "packetDelay_us": cfg.capture.packet_delay_us,
        },
        "EthernetConfig": {
            "DCA1000IPAddress": "192.168.33.180",
            "DCA1000ConfigPort": 4096,
            "DCA1000DataPort": 4098,
        },
        "EthernetConfigUpdate": {
            "systemIPAddress": "192.168.33.30",
            "DCA1000IPAddress": "192.168.33.180",
            "DCA1000MACAddress": "12:34:56:78:90:12",
            "DCA1000ConfigPort": 4096,
            "DCA1000DataPort": 4098,
        },
    }

    output_path.write_text(
        json.dumps(dca_config, indent=2) + "\n",
        encoding="utf-8",
    )
    return output_path
