-- AR1 Help Probe Script
-- run_id: 05ddfde7
local out_path = [[C:/Users/khams008/Documents/awr2944-fmcw-radar/exp_lau_probe/ti/probe_logs/05ddfde7_ar1_help_result.txt]]
local f = io.open(out_path, 'w')
if not f then return end
pcall(function()
    f:write('ChanNAdcConfig: type=' .. type(ar1.ChanNAdcConfig) .. ', tostring=' .. tostring(ar1.ChanNAdcConfig) .. '\n')
end)
pcall(function()
    f:write('LPModConfig: type=' .. type(ar1.LPModConfig) .. ', tostring=' .. tostring(ar1.LPModConfig) .. '\n')
end)
pcall(function()
    f:write('RfInit: type=' .. type(ar1.RfInit) .. ', tostring=' .. tostring(ar1.RfInit) .. '\n')
end)
pcall(function()
    f:write('DataPathConfig: type=' .. type(ar1.DataPathConfig) .. ', tostring=' .. tostring(ar1.DataPathConfig) .. '\n')
end)
pcall(function()
    f:write('LvdsClkConfig: type=' .. type(ar1.LvdsClkConfig) .. ', tostring=' .. tostring(ar1.LvdsClkConfig) .. '\n')
end)
pcall(function()
    f:write('LVDSLaneConfig: type=' .. type(ar1.LVDSLaneConfig) .. ', tostring=' .. tostring(ar1.LVDSLaneConfig) .. '\n')
end)
pcall(function()
    f:write('ProfileConfig: type=' .. type(ar1.ProfileConfig) .. ', tostring=' .. tostring(ar1.ProfileConfig) .. '\n')
end)
pcall(function()
    f:write('ChirpConfig: type=' .. type(ar1.ChirpConfig) .. ', tostring=' .. tostring(ar1.ChirpConfig) .. '\n')
end)
pcall(function()
    f:write('FrameConfig: type=' .. type(ar1.FrameConfig) .. ', tostring=' .. tostring(ar1.FrameConfig) .. '\n')
end)
pcall(function()
    f:write('StartFrame: type=' .. type(ar1.StartFrame) .. ', tostring=' .. tostring(ar1.StartFrame) .. '\n')
end)
pcall(function()
    f:write('StopFrame: type=' .. type(ar1.StopFrame) .. ', tostring=' .. tostring(ar1.StopFrame) .. '\n')
end)
pcall(function()
    f:write('SensorStart: type=' .. type(ar1.SensorStart) .. ', tostring=' .. tostring(ar1.SensorStart) .. '\n')
end)
pcall(function()
    f:write('SensorStop: type=' .. type(ar1.SensorStop) .. ', tostring=' .. tostring(ar1.SensorStop) .. '\n')
end)
pcall(function()
    f:write('CaptureCardConfig_EthInit: type=' .. type(ar1.CaptureCardConfig_EthInit) .. ', tostring=' .. tostring(ar1.CaptureCardConfig_EthInit) .. '\n')
end)
pcall(function()
    f:write('CaptureCardConfig_Mode: type=' .. type(ar1.CaptureCardConfig_Mode) .. ', tostring=' .. tostring(ar1.CaptureCardConfig_Mode) .. '\n')
end)
pcall(function()
    f:write('CaptureCardConfig_PacketDelay: type=' .. type(ar1.CaptureCardConfig_PacketDelay) .. ', tostring=' .. tostring(ar1.CaptureCardConfig_PacketDelay) .. '\n')
end)
pcall(function()
    f:write('CaptureCardConfig_StartRecord: type=' .. type(ar1.CaptureCardConfig_StartRecord) .. ', tostring=' .. tostring(ar1.CaptureCardConfig_StartRecord) .. '\n')
end)
pcall(function()
    f:write('CaptureCardConfig_StopRecord: type=' .. type(ar1.CaptureCardConfig_StopRecord) .. ', tostring=' .. tostring(ar1.CaptureCardConfig_StopRecord) .. '\n')
end)
pcall(function()
    f:write('SetDataConfig: type=' .. type(ar1.SetDataConfig) .. ', tostring=' .. tostring(ar1.SetDataConfig) .. '\n')
end)
pcall(function()
    f:write('GetDataConfig: type=' .. type(ar1.GetDataConfig) .. ', tostring=' .. tostring(ar1.GetDataConfig) .. '\n')
end)
f:close()