-- Connection-Only Stage Script
-- Generated by awr2944_dca mmws backend
-- run_id: b240ddc1-2903-47b4-b2e2-b9f688a52a46

local run_id = "b240ddc1-2903-47b4-b2e2-b9f688a52a46"
local out_path = "C:/Users/khams008/Documents/awr2944-fmcw-radar/exp_lau_probe/ti/probe_logs/connection_result.json"

local result = {
    run_id = run_id,
    executed = true,
    com_display = "COM6",
    com_number = 6,
    baud = 115200,
    timeout_ms = 1000,
    sop_control_called = false,
    sop_control_return = "nil",
    connect_called = false,
    connect_return = "nil",
    is_connected_called = false,
    is_connected_return = "nil",
    error = "nil"
}

local function safeLog(msg)
    if WriteToLog then
        pcall(function() WriteToLog(msg .. "\n") end)
    end
end

local function writeResult()
    local f = io.open(out_path, "w")
    if not f then
        safeLog("ERROR: Cannot write result to " .. out_path)
        return
    end
    f:write('{\n')
    f:write('  "run_id": "' .. result.run_id .. '",\n')
    f:write('  "executed": ' .. tostring(result.executed) .. ',\n')
    f:write('  "com_display": "' .. result.com_display .. '",\n')
    f:write('  "com_number": ' .. tostring(result.com_number) .. ',\n')
    f:write('  "baud": ' .. tostring(result.baud) .. ',\n')
    f:write('  "timeout_ms": ' .. tostring(result.timeout_ms) .. ',\n')
    f:write('  "sop_control_called": ' .. tostring(result.sop_control_called) .. ',\n')
    f:write('  "sop_control_return": ' .. tostring(result.sop_control_return) .. ',\n')
    f:write('  "connect_called": ' .. tostring(result.connect_called) .. ',\n')
    f:write('  "connect_return": ' .. tostring(result.connect_return) .. ',\n')
    f:write('  "is_connected_called": ' .. tostring(result.is_connected_called) .. ',\n')
    f:write('  "is_connected_return": ' .. tostring(result.is_connected_return) .. ',\n')
    if result.error == "nil" then
        f:write('  "error": null\n')
    else
        f:write('  "error": "' .. tostring(result.error) .. '"\n')
    end
    f:write('}\n')
    f:close()
    safeLog("Result written to " .. out_path)
end

local function run()
    if not ar1 then
        result.error = "ar1 API not available"
        return
    end

    -- SOPControl
    if ar1.SOPControl then
        result.sop_control_called = true
        safeLog("Calling ar1.SOPControl(2)...")
        local ok, ret = pcall(function() return ar1.SOPControl(2) end)
        if ok then
            result.sop_control_return = ret
            safeLog("SOPControl(2) returned: " .. tostring(ret))
        else
            result.error = "SOPControl crashed: " .. tostring(ret)
            return
        end
    end

    -- Connect
    if ar1.Connect then
        result.connect_called = true
        safeLog("Calling ar1.Connect(6, 115200, 1000)...")
        local ok, ret = pcall(function() return ar1.Connect(6, 115200, 1000) end)
        if ok then
            result.connect_return = ret
            safeLog("Connect returned: " .. tostring(ret))
        else
            result.error = "Connect crashed: " .. tostring(ret)
            return
        end
    end

    -- IsConnected (optional, non-critical)
    if ar1.IsConnected then
        result.is_connected_called = true
        local ok, ret = pcall(function() return ar1.IsConnected() end)
        if ok then
            result.is_connected_return = ret
            safeLog("IsConnected returned: " .. tostring(ret))
        end
    end
end

pcall(run)
writeResult()
