-- Lua/.NET Reflection Probe Script
-- Generated by awr2944_dca mmws internals
-- run_id: 7e40d287

local run_id = "7e40d287"
local out_path = [[C:\Users\khams008\Documents\awr2944-fmcw-radar\exp_lau_probe\ti\probe_logs\lua_dotnet_probe_result_7e40d287.json]]

local result = {
    run_id = run_id,
    executed = true,
    luanet_exists = false,
    forms_imported = false,
    open_forms = {},
    radar_api_found = false,
    controls = {}
}

local function safeLog(msg)
    if WriteToLog then
        pcall(function() WriteToLog(msg .. "\n") end)
    end
end

local function saveResult()
    local f = io.open(out_path, "w")
    if f then
        local lines = {
            "{\n",
            '  "run_id": "' .. tostring(result.run_id) .. '",\n',
            '  "executed": ' .. tostring(result.executed) .. ',\n',
            '  "luanet_exists": ' .. tostring(result.luanet_exists) .. ',\n',
            '  "forms_imported": ' .. tostring(result.forms_imported) .. ',\n',
            '  "radar_api_found": ' .. tostring(result.radar_api_found) .. ',\n',
            '  "open_forms": [\n'
        }
        
        for i, form in ipairs(result.open_forms) do
            local comma = (i == #result.open_forms) and "" or ","
            table.insert(lines, '    {"name": "' .. tostring(form.name) .. '", "text": "' .. tostring(form.text) .. '", "type": "' .. tostring(form.type) .. '"}' .. comma .. '\n')
        end
        table.insert(lines, '  ],\n')
        
        table.insert(lines, '  "controls": {\n')
        local i = 0
        local count = 0
        for k, v in pairs(result.controls) do count = count + 1 end
        
        for name, found in pairs(result.controls) do
            i = i + 1
            local comma = (i == count) and "" or ","
            table.insert(lines, '    "' .. tostring(name) .. '": ' .. tostring(found) .. comma .. '\n')
        end
        table.insert(lines, '  }\n')
        table.insert(lines, '}\n')
        
        for _, line in ipairs(lines) do
            f:write(line)
        end
        f:close()
    end
end

-- 1. Check luanet
if type(luanet) == "table" and type(luanet.import_type) == "function" then
    result.luanet_exists = true
    safeLog("luanet reflection is available.")
else
    safeLog("luanet reflection is NOT available.")
    saveResult()
    return
end

-- 2. Import Forms
local b, err = pcall(function()
    luanet.load_assembly("System.Windows.Forms")
    Application = luanet.import_type("System.Windows.Forms.Application")
end)

if b and Application then
    result.forms_imported = true
    safeLog("System.Windows.Forms.Application imported.")
else
    safeLog("Failed to import Forms: " .. tostring(err))
    saveResult()
    return
end

-- 3. Enumerate Forms
local b2, err2 = pcall(function()
    local forms = Application.OpenForms
    local count = forms.Count
    safeLog("Found " .. tostring(count) .. " open forms.")
    
    local target_form = nil
    
    for i=0, count-1 do
        local form = forms[i]
        local f_name = tostring(form.Name)
        local f_text = tostring(form.Text)
        local f_type = tostring(form:GetType().FullName)
        
        table.insert(result.open_forms, {
            name = f_name,
            text = f_text,
            type = f_type
        })
        
        if f_name == "frmAR1Main" or string.find(f_text, "RadarAPI") then
            target_form = form
            result.radar_api_found = true
        end
    end
    
    -- 4. Find specific controls
    if target_form then
        safeLog("RadarAPI form found. Searching for controls...")
        local controls_to_find = {
            "m_RadioBtn77GHzRadarDev",
            "m_RadioBtnxWR294x",
            "m_btnSetSop",
            "m_cboComPort",
            "m_cboBaudRate",
            "m_btnConnect",
            "m_btnRefreshPorts",
            "m_lblRS232UARTConnectivityStatus",
            "m_ConsoleText"
        }
        
        for _, name in ipairs(controls_to_find) do
            local found = target_form.Controls:Find(name, true)
            if found and found.Length > 0 then
                result.controls[name] = true
                safeLog("  Found: " .. name)
            else
                result.controls[name] = false
                safeLog("  MISSING: " .. name)
            end
        end
    else
        safeLog("RadarAPI form NOT found.")
    end
end)

if not b2 then
    safeLog("Error during enumeration: " .. tostring(err2))
end

saveResult()
