"""Lua script builder for mmWave Studio ar1 commands.

Generates stage-specific Lua scripts that are safe to run inside the
mmWave Studio Lua Shell.  Every generated script is validated against
the stage's forbidden-call list before being written to disk.
"""

from __future__ import annotations

import re
from pathlib import Path

from awr2944_dca.mmws.stages import StageName, get_all_forbidden_calls


def validate_script_safety(script_text: str, stage: StageName) -> list[str]:
    """Statically scan generated Lua for forbidden ar1 calls.

    Returns a list of violations (empty = safe).
    """
    forbidden = get_all_forbidden_calls(stage)
    violations: list[str] = []
    for i, line in enumerate(script_text.splitlines(), start=1):
        stripped = line.strip()
        if stripped.startswith("--"):
            continue
        for call in forbidden:
            if f"ar1.{call}" in stripped:
                violations.append(f"Line {i}: forbidden call ar1.{call} -> {stripped}")
    return violations


def build_connection_diag_script(
    run_id: str,
    com_num: int,
    baud: int = 921600,
    timeout_ms: int = 1000,
    result_dir: str = ".",
    steps: list[str] = None,
) -> str:
    """Generate a diagnostic connection Lua script.

    If `steps` is provided, only those steps are executed.
    Valid steps: "is_connected_initial", "sop", "connect", "is_connected_final", "disconnect".
    Writes step-by-step progress to connection_progress.jsonl.
    """
    if steps is None:
        steps = ["is_connected_initial", "sop", "connect", "is_connected_final"]

    result_path = result_dir.replace("\\", "/") + "/connection_result.json"
    progress_path = result_dir.replace("\\", "/") + "/connection_progress.jsonl"

    script = f"""\
-- Connection Diagnostics Script
-- Generated by awr2944_dca mmws backend
-- run_id: {run_id}
-- steps: {",".join(steps)}

local run_id = "{run_id}"
local out_path = "{result_path}"
local prog_path = "{progress_path}"

local result = {{
    run_id = run_id,
    executed = true,
    com_display = "COM{com_num}",
    com_number = {com_num},
    baud = {baud},
    timeout_ms = {timeout_ms},
    sop_control_called = false,
    sop_control_return = "null",
    connect_called = false,
    connect_return = "null",
    disconnect_called = false,
    disconnect_return = "null",
    is_connected_initial = "null",
    is_connected_final = "null",
    error = "null"
}}

local function safeLog(msg)
    if WriteToLog then
        pcall(function() WriteToLog(msg .. "\\n") end)
    end
end

local function writeProgress(step, data)
    local f = io.open(prog_path, "a")
    if f then
        local msg = '{{"step": "' .. step .. '"'
        if data then
            msg = msg .. ', "data": "' .. tostring(data):gsub('"', '\\\\"') .. '"'
        end
        msg = msg .. '}}\\n'
        f:write(msg)
        f:flush()
        f:close()
    end
end

local function writeResult()
    local f = io.open(out_path, "w")
    if not f then
        safeLog("ERROR: Cannot write result to " .. out_path)
        return
    end
    f:write('{{\\n')
    f:write('  "run_id": "' .. result.run_id .. '",\\n')
    f:write('  "executed": ' .. tostring(result.executed) .. ',\\n')
    f:write('  "com_display": "' .. result.com_display .. '",\\n')
    f:write('  "com_number": ' .. tostring(result.com_number) .. ',\\n')
    f:write('  "baud": ' .. tostring(result.baud) .. ',\\n')
    f:write('  "timeout_ms": ' .. tostring(result.timeout_ms) .. ',\\n')
    f:write('  "sop_control_called": ' .. tostring(result.sop_control_called) .. ',\\n')
    f:write('  "sop_control_return": ' .. tostring(result.sop_control_return) .. ',\\n')
    f:write('  "connect_called": ' .. tostring(result.connect_called) .. ',\\n')
    f:write('  "connect_return": ' .. tostring(result.connect_return) .. ',\\n')
    f:write('  "disconnect_called": ' .. tostring(result.disconnect_called) .. ',\\n')
    f:write('  "disconnect_return": ' .. tostring(result.disconnect_return) .. ',\\n')
    f:write('  "is_connected_initial": ' .. tostring(result.is_connected_initial) .. ',\\n')
    f:write('  "is_connected_final": ' .. tostring(result.is_connected_final) .. ',\\n')
    if result.error == "null" then
        f:write('  "error": null\\n')
    else
        f:write('  "error": "' .. tostring(result.error):gsub('"', '\\\\"') .. '"\\n')
    end
    f:write('}}\\n')
    f:close()
    safeLog("Result written to " .. out_path)
end

local function run()
    writeProgress("script_started")
    if not ar1 then
        result.error = "ar1 API not available"
        writeProgress("ar1_missing")
        return
    end
    writeProgress("ar1_available")
"""

    if "is_connected_initial" in steps:
        script += """
    -- Initial IsConnected
    if ar1.IsConnected then
        writeProgress("before_IsConnected_initial")
        local ok, ret = pcall(function() return ar1.IsConnected() end)
        if ok then
            result.is_connected_initial = tostring(ret)
        end
        writeProgress("after_IsConnected_initial", tostring(ret))
    end
"""

    if "disconnect" in steps:
        script += """
    -- Disconnect
    if ar1.Disconnect then
        result.disconnect_called = true
        writeProgress("before_Disconnect")
        safeLog("Calling ar1.Disconnect()...")
        local ok, ret = pcall(function() return ar1.Disconnect() end)
        if ok then
            result.disconnect_return = tostring(ret)
            writeProgress("after_Disconnect", tostring(ret))
            safeLog("Disconnect returned: " .. tostring(ret))
        else
            result.error = "Disconnect crashed: " .. tostring(ret)
            writeProgress("after_Disconnect", "error: " .. tostring(ret))
            return
        end
    end
"""

    if "sop" in steps:
        script += """
    -- SOPControl
    if ar1.SOPControl then
        result.sop_control_called = true
        writeProgress("before_SOPControl")
        safeLog("Calling ar1.SOPControl(2)...")
        local ok, ret = pcall(function() return ar1.SOPControl(2) end)
        if ok then
            result.sop_control_return = tostring(ret)
            writeProgress("after_SOPControl", tostring(ret))
            safeLog("SOPControl(2) returned: " .. tostring(ret))
        else
            result.error = "SOPControl crashed: " .. tostring(ret)
            writeProgress("after_SOPControl", "error: " .. tostring(ret))
            return
        end
    end
"""

    if "connect" in steps:
        script += f"""
    -- Connect
    if ar1.Connect then
        result.connect_called = true
        writeProgress("before_Connect")
        safeLog("Calling ar1.Connect({com_num}, {baud}, {timeout_ms})...")
        local ok, ret = pcall(function() return ar1.Connect({com_num}, {baud}, {timeout_ms}) end)
        if ok then
            result.connect_return = tostring(ret)
            writeProgress("after_Connect", tostring(ret))
            safeLog("Connect returned: " .. tostring(ret))
        else
            result.error = "Connect crashed: " .. tostring(ret)
            writeProgress("after_Connect", "error: " .. tostring(ret))
            return
        end
    end
"""

    if "is_connected_final" in steps:
        script += """
    -- Final IsConnected
    if ar1.IsConnected then
        writeProgress("before_IsConnected_final")
        local ok, ret = pcall(function() return ar1.IsConnected() end)
        if ok then
            result.is_connected_final = tostring(ret)
        end
        writeProgress("after_IsConnected_final", tostring(ret))
    end
"""

    script += """
    writeProgress("result_written")
end

-- Clear old progress file
local pf = io.open(prog_path, "w")
if pf then pf:close() end

pcall(run)
writeResult()
"""
    return script


def write_connection_diag_script(
    out_path: Path,
    run_id: str,
    com_num: int,
    baud: int = 921600,
    timeout_ms: int = 1000,
    steps: list[str] = None,
) -> None:
    """Generate and write a diagnostic connection-only Lua script with safety validation."""
    result_dir = str(out_path.parent.resolve())
    script = build_connection_diag_script(run_id, com_num, baud, timeout_ms, result_dir, steps)

    violations = validate_script_safety(script, StageName.CONNECTION_ONLY)
    if violations:
        raise RuntimeError(
            f"SAFETY VIOLATION: Generated connection script contains forbidden calls:\\n"
            + "\\n".join(violations)
        )

    out_path.write_text(script, encoding="utf-8")


def build_smoke_script(run_id: str, result_dir: str = ".") -> str:
    """Generate a harmless smoke-test Lua script.

    This script contains NO ar1 hardware calls.  It only:
    - Calls WriteToLog via pcall (to test logging)
    - Writes smoke_result.json via io.open
    - Proves the Python -> mmWave Studio -> Lua -> JSON -> Python path works

    Wrapped in xpcall so that if anything fails, it still tries to write
    an error result JSON.
    """
    result_path = result_dir.replace("\\", "/") + "/smoke_result.json"

    return f"""\
-- Smoke Test Script
-- Generated by awr2944_dca mmws backend
-- run_id: {run_id}
-- Contains NO ar1 hardware calls.

local run_id = "{run_id}"
local out_path = "{result_path}"

local function write_result(success, log_ok, err_msg)
    local f, ferr = io.open(out_path, "w")
    if f then
        f:write('{{\\n')
        f:write('  "run_id": "' .. run_id .. '",\\n')
        f:write('  "executed": true,\\n')
        f:write('  "log_available": ' .. tostring(log_ok) .. ',\\n')
        f:write('  "write_ok": true,\\n')
        if success then
            f:write('  "error": null\\n')
        else
            f:write('  "error": "' .. tostring(err_msg):gsub('"', '\\\\"') .. '"\\n')
        end
        f:write('}}\\n')
        f:close()
    end
end

local ok, err = xpcall(function()
    local log_ok = false

    -- Test WriteToLog
    if WriteToLog then
        local wok, werr = pcall(function()
            WriteToLog("SMOKE TEST: run_id=" .. run_id .. "\\n")
        end)
        log_ok = wok
    end

    write_result(true, log_ok, nil)
end, function(e)
    return tostring(e)
end)

if not ok then
    -- xpcall error handler: try to write error result
    pcall(write_result, false, false, err)
end
"""


def write_smoke_script(out_path: Path, run_id: str) -> None:
    """Generate and write the smoke test script."""
    result_dir = str(out_path.parent.resolve())
    script = build_smoke_script(run_id, result_dir)

    # Safety: verify no ar1 calls at all
    import re
    ar1_calls = re.findall(r"ar1\.\w+", script)
    if ar1_calls:
        raise RuntimeError(
            f"SAFETY VIOLATION: Smoke script contains ar1 calls: {ar1_calls}"
        )

    out_path.write_text(script, encoding="utf-8")


# ---------------------------------------------------------------------------
# lua-launch self-contained scripts
#
# These scripts are executed via mmWaveStudio.exe /lua BEFORE Startup.lua
# finishes.  They must NOT depend on WriteToLog, writeToLog, ar1, or any
# Startup.lua helper.  All output is via io.open only.
# ---------------------------------------------------------------------------


def build_lua_launch_smoke(run_id: str, result_path: str) -> str:
    """Generate a self-contained smoke script for lua-launch.

    No WriteToLog, no ar1, no Startup.lua dependency.
    Writes result JSON via io.open only.
    """
    result_path = result_path.replace("\\", "/")
    return f"""\
-- lua-launch smoke test
-- Self-contained: no WriteToLog, no ar1, no Startup.lua
-- run_id: {run_id}

local run_id = "{run_id}"
local out_path = [[{result_path}]]

local ok, err = pcall(function()
    local f = io.open(out_path, "w")
    if not f then
        error("Cannot open result file: " .. out_path)
    end
    f:write('{{\\n')
    f:write('  "run_id": "' .. run_id .. '",\\n')
    f:write('  "executed": true,\\n')
    f:write('  "write_ok": true,\\n')
    f:write('  "error": null\\n')
    f:write('}}\\n')
    f:close()
end)

if not ok then
    -- Last-ditch: try to write error result
    local f = io.open(out_path, "w")
    if f then
        f:write('{{\\n')
        f:write('  "run_id": "' .. run_id .. '",\\n')
        f:write('  "executed": false,\\n')
        f:write('  "write_ok": false,\\n')
        f:write('  "error": "' .. tostring(err):gsub('"', '\\\\"') .. '"\\n')
        f:write('}}\\n')
        f:close()
    end
end
"""


def build_lua_launch_env_probe(run_id: str, result_path: str) -> str:
    """Generate a self-contained environment probe for lua-launch.

    Reports:
      _VERSION, type(ar1), type(WriteToLog), type(writeToLog),
      package.path, whether io.open works.
    """
    result_path = result_path.replace("\\", "/")
    # The esc() function must escape in this order:
    #   1. backslash -> \\   (must be first!)
    #   2. quote -> \"
    #   3. newline -> \\n
    #   4. carriage return -> \\r
    #   5. tab -> \\t
    # In the f-string, Lua sees the literal gsub patterns.
    return f"""\
-- lua-launch env-probe
-- Self-contained: no WriteToLog, no ar1, no Startup.lua
-- run_id: {run_id}

local run_id = "{run_id}"
local out_path = [[{result_path}]]

local function esc(s)
    if s == nil then return "null" end
    s = tostring(s)
    s = s:gsub("\\\\", "\\\\\\\\")
    s = s:gsub('"', '\\\\"')
    s = s:gsub("\\r", "\\\\r")
    s = s:gsub("\\n", "\\\\n")
    s = s:gsub("\\t", "\\\\t")
    return '"' .. s .. '"'
end

local ok, err = pcall(function()
    local lua_version = _VERSION or "unknown"
    local ar1_type = type(ar1)
    local ar1_connect_exists = false
    if type(ar1) == "table" and ar1.Connect then
        ar1_connect_exists = true
    end
    local write_to_log_type = type(WriteToLog)
    local write_to_log_lower_type = type(writeToLog)
    local pkg_path = package.path or "nil"

    local f = io.open(out_path, "w")
    if not f then
        error("Cannot open result file: " .. out_path)
    end
    f:write('{{\n')
    f:write('  "run_id": ' .. esc(run_id) .. ',\n')
    f:write('  "executed": true,\n')
    f:write('  "_VERSION": ' .. esc(lua_version) .. ',\n')
    f:write('  "type_ar1": ' .. esc(ar1_type) .. ',\n')
    f:write('  "ar1_connect_exists": ' .. tostring(ar1_connect_exists) .. ',\n')
    f:write('  "type_WriteToLog": ' .. esc(write_to_log_type) .. ',\n')
    f:write('  "type_writeToLog": ' .. esc(write_to_log_lower_type) .. ',\n')
    f:write('  "package_path": ' .. esc(pkg_path) .. ',\n')
    f:write('  "io_open_works": true,\n')
    f:write('  "error": null\n')
    f:write('}}\n')
    f:close()
end)

if not ok then
    local f = io.open(out_path, "w")
    if f then
        f:write('{{\n')
        f:write('  "run_id": ' .. esc(run_id) .. ',\n')
        f:write('  "executed": false,\n')
        f:write('  "error": ' .. esc(tostring(err)) .. '\n')
        f:write('}}\n')
        f:close()
    end
end
"""
