"""Lua script builder for mmWave Studio ar1 commands.

Generates stage-specific Lua scripts that are safe to run inside the
mmWave Studio Lua Shell.  Every generated script is validated against
the stage's forbidden-call list before being written to disk.
"""

from __future__ import annotations

import re
from pathlib import Path

from awr2944_dca.mmws.stages import StageName, get_all_forbidden_calls


def validate_script_safety(script_text: str, stage: StageName) -> list[str]:
    """Statically scan generated Lua for forbidden ar1 calls.

    Returns a list of violations (empty = safe).
    """
    forbidden = get_all_forbidden_calls(stage)
    violations: list[str] = []
    for i, line in enumerate(script_text.splitlines(), start=1):
        stripped = line.strip()
        if stripped.startswith("--"):
            continue
        for call in forbidden:
            if f"ar1.{call}" in stripped:
                violations.append(f"Line {i}: forbidden call ar1.{call} -> {stripped}")
    return violations


def build_connection_script(
    run_id: str,
    com_num: int,
    baud: int = 921600,
    timeout_ms: int = 1000,
    result_dir: str = ".",
) -> str:
    """Generate a connection-only Lua script.

    Allowed calls: ar1.SOPControl, ar1.Connect, ar1.IsConnected.
    Uses pcall around every ar1 call to prevent crashes.
    Writes connection_result.json with the matching run_id.
    """
    result_path = result_dir.replace("\\", "/") + "/connection_result.json"

    script = f"""\
-- Connection-Only Stage Script
-- Generated by awr2944_dca mmws backend
-- run_id: {run_id}

local run_id = "{run_id}"
local out_path = "{result_path}"

local result = {{
    run_id = run_id,
    executed = true,
    com_display = "COM{com_num}",
    com_number = {com_num},
    baud = {baud},
    timeout_ms = {timeout_ms},
    sop_control_called = false,
    sop_control_return = "nil",
    connect_called = false,
    connect_return = "nil",
    is_connected_called = false,
    is_connected_return = "nil",
    error = "nil"
}}

local function safeLog(msg)
    if WriteToLog then
        pcall(function() WriteToLog(msg .. "\\n") end)
    end
end

local function writeResult()
    local f = io.open(out_path, "w")
    if not f then
        safeLog("ERROR: Cannot write result to " .. out_path)
        return
    end
    f:write('{{\\n')
    f:write('  "run_id": "' .. result.run_id .. '",\\n')
    f:write('  "executed": ' .. tostring(result.executed) .. ',\\n')
    f:write('  "com_display": "' .. result.com_display .. '",\\n')
    f:write('  "com_number": ' .. tostring(result.com_number) .. ',\\n')
    f:write('  "baud": ' .. tostring(result.baud) .. ',\\n')
    f:write('  "timeout_ms": ' .. tostring(result.timeout_ms) .. ',\\n')
    f:write('  "sop_control_called": ' .. tostring(result.sop_control_called) .. ',\\n')
    f:write('  "sop_control_return": ' .. tostring(result.sop_control_return) .. ',\\n')
    f:write('  "connect_called": ' .. tostring(result.connect_called) .. ',\\n')
    f:write('  "connect_return": ' .. tostring(result.connect_return) .. ',\\n')
    f:write('  "is_connected_called": ' .. tostring(result.is_connected_called) .. ',\\n')
    f:write('  "is_connected_return": ' .. tostring(result.is_connected_return) .. ',\\n')
    if result.error == "nil" then
        f:write('  "error": null\\n')
    else
        f:write('  "error": "' .. tostring(result.error) .. '"\\n')
    end
    f:write('}}\\n')
    f:close()
    safeLog("Result written to " .. out_path)
end

local function run()
    if not ar1 then
        result.error = "ar1 API not available"
        return
    end

    -- SOPControl
    if ar1.SOPControl then
        result.sop_control_called = true
        safeLog("Calling ar1.SOPControl(2)...")
        local ok, ret = pcall(function() return ar1.SOPControl(2) end)
        if ok then
            result.sop_control_return = ret
            safeLog("SOPControl(2) returned: " .. tostring(ret))
        else
            result.error = "SOPControl crashed: " .. tostring(ret)
            return
        end
    end

    -- Connect
    if ar1.Connect then
        result.connect_called = true
        safeLog("Calling ar1.Connect({com_num}, {baud}, {timeout_ms})...")
        local ok, ret = pcall(function() return ar1.Connect({com_num}, {baud}, {timeout_ms}) end)
        if ok then
            result.connect_return = ret
            safeLog("Connect returned: " .. tostring(ret))
        else
            result.error = "Connect crashed: " .. tostring(ret)
            return
        end
    end

    -- IsConnected (optional, non-critical)
    if ar1.IsConnected then
        result.is_connected_called = true
        local ok, ret = pcall(function() return ar1.IsConnected() end)
        if ok then
            result.is_connected_return = ret
            safeLog("IsConnected returned: " .. tostring(ret))
        end
    end
end

pcall(run)
writeResult()
"""
    return script


def write_connection_script(
    out_path: Path,
    run_id: str,
    com_num: int,
    baud: int = 921600,
    timeout_ms: int = 1000,
) -> None:
    """Generate and write a connection-only Lua script with safety validation."""
    result_dir = str(out_path.parent.resolve())
    script = build_connection_script(run_id, com_num, baud, timeout_ms, result_dir)

    # Safety gate: verify no forbidden calls leaked in
    violations = validate_script_safety(script, StageName.CONNECTION_ONLY)
    if violations:
        raise RuntimeError(
            f"SAFETY VIOLATION: Generated connection script contains forbidden calls:\\n"
            + "\\n".join(violations)
        )

    out_path.write_text(script, encoding="utf-8")
