-- Smoke Test Script
-- Generated by awr2944_dca mmws backend
-- run_id: a9cfc073-95d7-4048-949c-3ce980359d06
-- Contains NO ar1 hardware calls.

local run_id = "a9cfc073-95d7-4048-949c-3ce980359d06"
local out_path = "C:/Users/khams008/Documents/awr2944-fmcw-radar/.pytest-tmp/test_bridge_smoke_generation0/smoke_result.json"

local function write_result(success, log_ok, err_msg)
    local f, ferr = io.open(out_path, "w")
    if f then
        f:write('{\n')
        f:write('  "run_id": "' .. run_id .. '",\n')
        f:write('  "executed": true,\n')
        f:write('  "log_available": ' .. tostring(log_ok) .. ',\n')
        f:write('  "write_ok": true,\n')
        if success then
            f:write('  "error": null\n')
        else
            f:write('  "error": "' .. tostring(err_msg):gsub('"', '\\"') .. '"\n')
        end
        f:write('}\n')
        f:close()
    end
end

local ok, err = xpcall(function()
    local log_ok = false

    -- Test WriteToLog
    if WriteToLog then
        local wok, werr = pcall(function()
            WriteToLog("SMOKE TEST: run_id=" .. run_id .. "\n")
        end)
        log_ok = wok
    end

    write_result(true, log_ok, nil)
end, function(e)
    return tostring(e)
end)

if not ok then
    -- xpcall error handler: try to write error result
    pcall(write_result, false, false, err)
end
