-- Connection-Only Hardware Probe
-- Generated by awr2944_dca

local run_id = "run-123"
local out_path = "C:/Users/khams008/Documents/awr2944-fmcw-radar/.pytest_tmp/test_connection_probe_safety0/connection_result.json"

local function escapeJSON(s)
    if s == nil then return "null" end
    s = tostring(s)
    s = string.gsub(s, '\\', '\\\\')
    s = string.gsub(s, '"', '\\"')
    s = string.gsub(s, '\n', '\\n')
    s = string.gsub(s, '\r', '\\r')
    return s
end

local result = {
    run_id = run_id,
    executed = true,
    com_display = "COM" .. tostring(8),
    com_number = 8,
    baud = 921600,
    timeout_ms = 1000,
    sop_control_called = false,
    sop_control_return = nil,
    connect_called = false,
    connect_return = nil,
    is_connected_called = false,
    is_connected_return = nil,
    error = nil
}

local function writeResult()
    local f, err = io.open(out_path, "w")
    if f then
        f:write('{\n')
        f:write('  "run_id": "' .. result.run_id .. '",\n')
        f:write('  "executed": ' .. tostring(result.executed) .. ',\n')
        f:write('  "com_display": "' .. result.com_display .. '",\n')
        f:write('  "com_number": ' .. tostring(result.com_number) .. ',\n')
        f:write('  "baud": ' .. tostring(result.baud) .. ',\n')
        f:write('  "timeout_ms": ' .. tostring(result.timeout_ms) .. ',\n')
        f:write('  "sop_control_called": ' .. tostring(result.sop_control_called) .. ',\n')
        f:write('  "sop_control_return": ' .. escapeJSON(result.sop_control_return) .. ',\n')
        f:write('  "connect_called": ' .. tostring(result.connect_called) .. ',\n')
        f:write('  "connect_return": ' .. escapeJSON(result.connect_return) .. ',\n')
        f:write('  "is_connected_called": ' .. tostring(result.is_connected_called) .. ',\n')
        f:write('  "is_connected_return": ' .. escapeJSON(result.is_connected_return) .. ',\n')
        if result.error then
            f:write('  "error": "' .. escapeJSON(result.error) .. '"\n')
        else
            f:write('  "error": null\n')
        end
        f:write('}\n')
        f:close()
    end
end

local function safeLog(msg)
    if ar1 and ar1.WriteToLog then
        pcall(function() ar1.WriteToLog(msg .. "\n") end)
    end
end

local function run()
    if not ar1 then
        result.error = "ar1 API not available"
        return
    end
    
    -- SOP Control
    if ar1.SOPControl then
        result.sop_control_called = true
        local status, ret = pcall(function() return ar1.SOPControl(2) end)
        if status then
            result.sop_control_return = ret
            safeLog("SOPControl(2) returned: " .. tostring(ret))
        else
            result.error = "SOPControl crashed: " .. tostring(ret)
            return
        end
    end
    
    -- Connect
    if ar1.Connect then
        result.connect_called = true
        local status, ret = pcall(function() return ar1.Connect(8, 921600, 1000) end)
        if status then
            result.connect_return = ret
            safeLog("Connect(8, 921600, 1000) returned: " .. tostring(ret))
        else
            result.error = "Connect crashed: " .. tostring(ret)
            return
        end
    end
    
    -- IsConnected
    if ar1.IsConnected then
        result.is_connected_called = true
        local status, ret = pcall(function() return ar1.IsConnected() end)
        if status then
            result.is_connected_return = ret
            safeLog("IsConnected() returned: " .. tostring(ret))
        else
            -- Ignore crash in IsConnected, not as critical
            result.error = (result.error or "") .. " | IsConnected crashed"
        end
    end
end

pcall(run)
writeResult()
