-- Connection Diagnostics Script
-- Generated by awr2944_dca mmws backend
-- run_id: run-123
-- steps: is_connected_initial,sop,connect,is_connected_final

local run_id = "run-123"
local out_path = "C:/Users/khams008/Documents/awr2944-fmcw-radar/.pytest-tmp3/test_write_connection_diag_scr0/connection_result.json"
local prog_path = "C:/Users/khams008/Documents/awr2944-fmcw-radar/.pytest-tmp3/test_write_connection_diag_scr0/connection_progress.jsonl"

local result = {
    run_id = run_id,
    executed = true,
    com_display = "COM6",
    com_number = 6,
    baud = 921600,
    timeout_ms = 1000,
    sop_control_called = false,
    sop_control_return = "null",
    connect_called = false,
    connect_return = "null",
    disconnect_called = false,
    disconnect_return = "null",
    is_connected_initial = "null",
    is_connected_final = "null",
    error = "null"
}

local function safeLog(msg)
    if WriteToLog then
        pcall(function() WriteToLog(msg .. "\n") end)
    end
end

local function writeProgress(step, data)
    local f = io.open(prog_path, "a")
    if f then
        local msg = '{"step": "' .. step .. '"'
        if data then
            msg = msg .. ', "data": "' .. tostring(data):gsub('"', '\\"') .. '"'
        end
        msg = msg .. '}\n'
        f:write(msg)
        f:flush()
        f:close()
    end
end

local function writeResult()
    local f = io.open(out_path, "w")
    if not f then
        safeLog("ERROR: Cannot write result to " .. out_path)
        return
    end
    f:write('{\n')
    f:write('  "run_id": "' .. result.run_id .. '",\n')
    f:write('  "executed": ' .. tostring(result.executed) .. ',\n')
    f:write('  "com_display": "' .. result.com_display .. '",\n')
    f:write('  "com_number": ' .. tostring(result.com_number) .. ',\n')
    f:write('  "baud": ' .. tostring(result.baud) .. ',\n')
    f:write('  "timeout_ms": ' .. tostring(result.timeout_ms) .. ',\n')
    f:write('  "sop_control_called": ' .. tostring(result.sop_control_called) .. ',\n')
    f:write('  "sop_control_return": ' .. tostring(result.sop_control_return) .. ',\n')
    f:write('  "connect_called": ' .. tostring(result.connect_called) .. ',\n')
    f:write('  "connect_return": ' .. tostring(result.connect_return) .. ',\n')
    f:write('  "disconnect_called": ' .. tostring(result.disconnect_called) .. ',\n')
    f:write('  "disconnect_return": ' .. tostring(result.disconnect_return) .. ',\n')
    f:write('  "is_connected_initial": ' .. tostring(result.is_connected_initial) .. ',\n')
    f:write('  "is_connected_final": ' .. tostring(result.is_connected_final) .. ',\n')
    if result.error == "null" then
        f:write('  "error": null\n')
    else
        f:write('  "error": "' .. tostring(result.error):gsub('"', '\\"') .. '"\n')
    end
    f:write('}\n')
    f:close()
    safeLog("Result written to " .. out_path)
end

local function run()
    writeProgress("script_started")
    if not ar1 then
        result.error = "ar1 API not available"
        writeProgress("ar1_missing")
        return
    end
    writeProgress("ar1_available")

    -- Initial IsConnected
    if ar1.IsConnected then
        writeProgress("before_IsConnected_initial")
        local ok, ret = pcall(function() return ar1.IsConnected() end)
        if ok then
            result.is_connected_initial = tostring(ret)
        end
        writeProgress("after_IsConnected_initial", tostring(ret))
    end

    -- SOPControl
    if ar1.SOPControl then
        result.sop_control_called = true
        writeProgress("before_SOPControl")
        safeLog("Calling ar1.SOPControl(2)...")
        local ok, ret = pcall(function() return ar1.SOPControl(2) end)
        if ok then
            result.sop_control_return = tostring(ret)
            writeProgress("after_SOPControl", tostring(ret))
            safeLog("SOPControl(2) returned: " .. tostring(ret))
        else
            result.error = "SOPControl crashed: " .. tostring(ret)
            writeProgress("after_SOPControl", "error: " .. tostring(ret))
            return
        end
    end

    -- Connect
    if ar1.Connect then
        result.connect_called = true
        writeProgress("before_Connect")
        safeLog("Calling ar1.Connect(6, 921600, 1000)...")
        local ok, ret = pcall(function() return ar1.Connect(6, 921600, 1000) end)
        if ok then
            result.connect_return = tostring(ret)
            writeProgress("after_Connect", tostring(ret))
            safeLog("Connect returned: " .. tostring(ret))
        else
            result.error = "Connect crashed: " .. tostring(ret)
            writeProgress("after_Connect", "error: " .. tostring(ret))
            return
        end
    end

    -- Final IsConnected
    if ar1.IsConnected then
        writeProgress("before_IsConnected_final")
        local ok, ret = pcall(function() return ar1.IsConnected() end)
        if ok then
            result.is_connected_final = tostring(ret)
        end
        writeProgress("after_IsConnected_final", tostring(ret))
    end

    writeProgress("result_written")
end

-- Clear old progress file
local pf = io.open(prog_path, "w")
if pf then pf:close() end

pcall(run)
writeResult()
