"""Internal reflection and diagnostic backends for mmWave Studio."""

from __future__ import annotations

def build_lua_dotnet_probe_script(run_id: str, result_path: str) -> str:
    """Generate a Lua script that tests luanet reflection inside mmWave Studio.
    
    The script attempts to:
    1. Import System.Windows.Forms
    2. Enumerate Application.OpenForms
    3. Look for 'RadarAPI' / 'frmAR1Main'
    4. Find specific Connection tab controls via Controls.Find()
    """
    script = f"""\
-- Lua/.NET Reflection Probe Script
-- Generated by awr2944_dca mmws internals
-- run_id: {run_id}

local run_id = "{run_id}"
local out_path = [[{result_path.replace('\\\\', '/')}]]

local result = {{
    run_id = run_id,
    executed = true,
    luanet_exists = false,
    forms_imported = false,
    open_forms = {{}},
    radar_api_found = false,
    controls = {{}}
}}

local function safeLog(msg)
    if WriteToLog then
        pcall(function() WriteToLog(msg .. "\\n") end)
    end
end

local function saveResult()
    local f = io.open(out_path, "w")
    if f then
        local lines = {{
            "{{\\n",
            '  "run_id": "' .. tostring(result.run_id) .. '",\\n',
            '  "executed": ' .. tostring(result.executed) .. ',\\n',
            '  "luanet_exists": ' .. tostring(result.luanet_exists) .. ',\\n',
            '  "forms_imported": ' .. tostring(result.forms_imported) .. ',\\n',
            '  "radar_api_found": ' .. tostring(result.radar_api_found) .. ',\\n',
            '  "open_forms": [\\n'
        }}
        
        for i, form in ipairs(result.open_forms) do
            local comma = (i == #result.open_forms) and "" or ","
            table.insert(lines, '    {{"name": "' .. tostring(form.name) .. '", "text": "' .. tostring(form.text) .. '", "type": "' .. tostring(form.type) .. '"}}' .. comma .. '\\n')
        end
        table.insert(lines, '  ],\\n')
        
        table.insert(lines, '  "controls": {{\\n')
        local i = 0
        local count = 0
        for k, v in pairs(result.controls) do count = count + 1 end
        
        for name, found in pairs(result.controls) do
            i = i + 1
            local comma = (i == count) and "" or ","
            table.insert(lines, '    "' .. tostring(name) .. '": ' .. tostring(found) .. comma .. '\\n')
        end
        table.insert(lines, '  }}\\n')
        table.insert(lines, '}}\\n')
        
        for _, line in ipairs(lines) do
            f:write(line)
        end
        f:close()
    end
end

-- 1. Check luanet
if type(luanet) == "table" and type(luanet.import_type) == "function" then
    result.luanet_exists = true
    safeLog("luanet reflection is available.")
else
    safeLog("luanet reflection is NOT available.")
    saveResult()
    return
end

-- 2. Import Forms
local b, err = pcall(function()
    luanet.load_assembly("System.Windows.Forms")
    Application = luanet.import_type("System.Windows.Forms.Application")
end)

if b and Application then
    result.forms_imported = true
    safeLog("System.Windows.Forms.Application imported.")
else
    safeLog("Failed to import Forms: " .. tostring(err))
    saveResult()
    return
end

-- 3. Enumerate Forms
local b2, err2 = pcall(function()
    local forms = Application.OpenForms
    local count = forms.Count
    safeLog("Found " .. tostring(count) .. " open forms.")
    
    local target_form = nil
    
    for i=0, count-1 do
        local form = forms[i]
        local f_name = tostring(form.Name)
        local f_text = tostring(form.Text)
        local f_type = tostring(form:GetType().FullName)
        
        table.insert(result.open_forms, {{
            name = f_name,
            text = f_text,
            type = f_type
        }})
        
        if f_name == "frmAR1Main" or string.find(f_text, "RadarAPI") then
            target_form = form
            result.radar_api_found = true
        end
    end
    
    -- 4. Find specific controls
    if target_form then
        safeLog("RadarAPI form found. Searching for controls...")
        local controls_to_find = {{
            "m_RadioBtn77GHzRadarDev",
            "m_RadioBtnxWR294x",
            "m_btnSetSop",
            "m_cboComPort",
            "m_cboBaudRate",
            "m_btnConnect",
            "m_btnRefreshPorts",
            "m_lblRS232UARTConnectivityStatus",
            "m_ConsoleText"
        }}
        
        for _, name in ipairs(controls_to_find) do
            local found = target_form.Controls:Find(name, true)
            if found and found.Length > 0 then
                result.controls[name] = true
                safeLog("  Found: " .. name)
            else
                result.controls[name] = false
                safeLog("  MISSING: " .. name)
            end
        end
    else
        safeLog("RadarAPI form NOT found.")
    end
end)

if not b2 then
    safeLog("Error during enumeration: " .. tostring(err2))
end

saveResult()
"""
    return script


def build_lua_dotnet_connect_script(run_id: str, result_path: str, com: str, baud: int) -> str:
    """Generate a Lua script that leverages luanet to connect directly via WinForms controls."""
    script = f"""\
-- Lua/.NET WinForms Connection Script
-- Generated by awr2944_dca mmws internals
-- run_id: {run_id}

local run_id = "{run_id}"
local out_path = [[{result_path.replace('\\\\', '/')}]]
local target_com = "{com}"
local target_baud = "{baud}"

local result = {{
    run_id = run_id,
    executed = true,
    success = false,
    error = "",
    status_text = ""
}}

local function saveResult()
    local f = io.open(out_path, "w")
    if f then
        local lines = {{
            "{{\\n",
            '  "run_id": "' .. tostring(result.run_id) .. '",\\n',
            '  "executed": ' .. tostring(result.executed) .. ',\\n',
            '  "success": ' .. tostring(result.success) .. ',\\n',
            '  "error": "' .. tostring(result.error):gsub('"', '\\\\"') .. '",\\n',
            '  "status_text": "' .. tostring(result.status_text):gsub('"', '\\\\"') .. '"\\n',
            '}}\\n'
        }}
        for _, line in ipairs(lines) do f:write(line) end
        f:close()
    end
end

local function doConnect()
    if type(luanet) ~= "table" then return false, "luanet not available" end
    luanet.load_assembly("System.Windows.Forms")
    local Application = luanet.import_type("System.Windows.Forms.Application")
    if not Application then return false, "Could not import Application" end
    
    local forms = Application.OpenForms
    local target_form = nil
    for i=0, forms.Count-1 do
        local form = forms[i]
        if form.Name == "frmAR1Main" or string.find(tostring(form.Text), "RadarAPI") then
            target_form = form
            break
        end
    end
    
    if not target_form then return false, "RadarAPI form not found" end
    
    local function getCtrl(name)
        local arr = target_form.Controls:Find(name, true)
        if arr and arr.Length > 0 then return arr[0] end
        return nil
    end
    
    local rdo77 = getCtrl("m_RadioBtn77GHzRadarDev")
    local rdoDev = getCtrl("m_RadioBtnxWR294x")
    local btnSet = getCtrl("m_btnSetSop")
    local cboCom = getCtrl("m_cboComPort")
    local cboBaud = getCtrl("m_cboBaudRate")
    local btnConn = getCtrl("m_btnConnect")
    local rtbOut = getCtrl("m_ConsoleText")
    
    if not (rdo77 and rdoDev and btnSet and cboCom and cboBaud and btnConn and rtbOut) then
        return false, "One or more critical controls missing"
    end
    
    -- 1. Select 77GHz
    rdo77.Checked = true
    
    -- 2. Select Device
    rdoDev.Checked = true
    
    -- 3. Click Set(1)
    btnSet:PerformClick()
    
    -- Wait/poll for Set(1) completion in output log
    local setOk = false
    for i=1, 30 do
        local txt = tostring(rtbOut.Text)
        if string.find(txt, "SOPControl") or string.find(txt, "FullReset") then
            setOk = true
            break
        end
        RSTD.Sleep(1000)
    end
    
    if not setOk then return false, "Set(1) did not complete (timeout)" end
    
    -- 4. Set COM/Baud
    -- Needs careful setting via Text or SelectedItem
    cboCom.Text = target_com
    cboBaud.Text = tostring(target_baud)
    
    -- 5. Click Connect
    btnConn:PerformClick()
    
    -- Poll for success
    local connOk = false
    local lastStatus = ""
    for i=1, 15 do
        local txt = tostring(rtbOut.Text)
        -- Find last line containing "Device Status"
        for line in string.gmatch(txt, "[^\\r\\n]+") do
            if string.find(line, "Device Status") and string.find(line, "/") then
                lastStatus = line
            end
        end
        if string.find(lastStatus, "AWR2944") and string.find(lastStatus, "SOP:2") then
            connOk = true
            break
        end
        RSTD.Sleep(1000)
    end
    
    if connOk then
        result.status_text = lastStatus
        return true, ""
    else
        result.status_text = lastStatus
        return false, "Connection failed or timeout. Last status: " .. lastStatus
    end
end

local ok, err = pcall(function()
    local success, msg = doConnect()
    result.success = success
    if not success then result.error = msg end
end)

if not ok then
    result.success = false
    result.error = "Script crash: " .. tostring(err)
end

saveResult()
"""
    return script
