"""Lua script builder for mmWave Studio ar1 commands.

Generates stage-specific Lua scripts that are safe to run inside the
mmWave Studio Lua Shell.  Every generated script is validated against
the stage's forbidden-call list before being written to disk.
"""

from __future__ import annotations

import re
from pathlib import Path

from awr2944_dca.mmws.stages import StageName, get_all_forbidden_calls


def validate_script_safety(script_text: str, stage: StageName) -> list[str]:
    """Statically scan generated Lua for forbidden ar1 calls.

    Returns a list of violations (empty = safe).
    """
    forbidden = get_all_forbidden_calls(stage)
    violations: list[str] = []
    for i, line in enumerate(script_text.splitlines(), start=1):
        stripped = line.strip()
        if stripped.startswith("--"):
            continue
        for call in forbidden:
            if f"ar1.{call}" in stripped:
                violations.append(f"Line {i}: forbidden call ar1.{call} -> {stripped}")
    return violations


def build_connection_diag_script(
    run_id: str,
    com_num: int,
    baud: int = 921600,
    timeout_ms: int = 1000,
    result_dir: str = ".",
    steps: list[str] = None,
) -> str:
    """Generate a diagnostic connection Lua script.

    If `steps` is provided, only those steps are executed.
    Valid steps: "is_connected_initial", "sop", "connect", "is_connected_final", "disconnect".
    Writes step-by-step progress to connection_progress.jsonl.
    """
    if steps is None:
        steps = ["is_connected_initial", "sop", "connect", "is_connected_final"]

    result_path = result_dir.replace("\\", "/") + "/connection_result.json"
    progress_path = result_dir.replace("\\", "/") + "/connection_progress.jsonl"

    script = f"""\
-- Connection Diagnostics Script
-- Generated by awr2944_dca mmws backend
-- run_id: {run_id}
-- steps: {",".join(steps)}

local run_id = "{run_id}"
local out_path = "{result_path}"
local prog_path = "{progress_path}"

local result = {{
    run_id = run_id,
    executed = true,
    com_display = "COM{com_num}",
    com_number = {com_num},
    baud = {baud},
    timeout_ms = {timeout_ms},
    sop_control_called = false,
    sop_control_return = "null",
    connect_called = false,
    connect_return = "null",
    disconnect_called = false,
    disconnect_return = "null",
    is_connected_initial = "null",
    is_connected_final = "null",
    error = "null"
}}

local function safeLog(msg)
    if WriteToLog then
        pcall(function() WriteToLog(msg .. "\\n") end)
    end
end

local function writeProgress(step, data)
    local f = io.open(prog_path, "a")
    if f then
        local msg = '{{"step": "' .. step .. '"'
        if data then
            msg = msg .. ', "data": "' .. tostring(data):gsub('"', '\\\\"') .. '"'
        end
        msg = msg .. '}}\\n'
        f:write(msg)
        f:flush()
        f:close()
    end
end

local function writeResult()
    local f = io.open(out_path, "w")
    if not f then
        safeLog("ERROR: Cannot write result to " .. out_path)
        return
    end
    f:write('{{\\n')
    f:write('  "run_id": "' .. result.run_id .. '",\\n')
    f:write('  "executed": ' .. tostring(result.executed) .. ',\\n')
    f:write('  "com_display": "' .. result.com_display .. '",\\n')
    f:write('  "com_number": ' .. tostring(result.com_number) .. ',\\n')
    f:write('  "baud": ' .. tostring(result.baud) .. ',\\n')
    f:write('  "timeout_ms": ' .. tostring(result.timeout_ms) .. ',\\n')
    f:write('  "sop_control_called": ' .. tostring(result.sop_control_called) .. ',\\n')
    f:write('  "sop_control_return": ' .. tostring(result.sop_control_return) .. ',\\n')
    f:write('  "connect_called": ' .. tostring(result.connect_called) .. ',\\n')
    f:write('  "connect_return": ' .. tostring(result.connect_return) .. ',\\n')
    f:write('  "disconnect_called": ' .. tostring(result.disconnect_called) .. ',\\n')
    f:write('  "disconnect_return": ' .. tostring(result.disconnect_return) .. ',\\n')
    f:write('  "is_connected_initial": ' .. tostring(result.is_connected_initial) .. ',\\n')
    f:write('  "is_connected_final": ' .. tostring(result.is_connected_final) .. ',\\n')
    if result.error == "null" then
        f:write('  "error": null\\n')
    else
        f:write('  "error": "' .. tostring(result.error):gsub('"', '\\\\"') .. '"\\n')
    end
    f:write('}}\\n')
    f:close()
    safeLog("Result written to " .. out_path)
end

local function run()
    writeProgress("script_started")
    if not ar1 then
        result.error = "ar1 API not available"
        writeProgress("ar1_missing")
        return
    end
    writeProgress("ar1_available")
"""

    if "is_connected_initial" in steps:
        script += """
    -- Initial IsConnected
    if ar1.IsConnected then
        writeProgress("before_IsConnected_initial")
        local ok, ret = pcall(function() return ar1.IsConnected() end)
        if ok then
            result.is_connected_initial = tostring(ret)
        end
        writeProgress("after_IsConnected_initial", tostring(ret))
    end
"""

    if "disconnect" in steps:
        script += """
    -- Disconnect
    if ar1.Disconnect then
        result.disconnect_called = true
        writeProgress("before_Disconnect")
        safeLog("Calling ar1.Disconnect()...")
        local ok, ret = pcall(function() return ar1.Disconnect() end)
        if ok then
            result.disconnect_return = tostring(ret)
            writeProgress("after_Disconnect", tostring(ret))
            safeLog("Disconnect returned: " .. tostring(ret))
        else
            result.error = "Disconnect crashed: " .. tostring(ret)
            writeProgress("after_Disconnect", "error: " .. tostring(ret))
            return
        end
    end
"""

    if "sop" in steps:
        script += """
    -- SOPControl
    if ar1.SOPControl then
        result.sop_control_called = true
        writeProgress("before_SOPControl")
        safeLog("Calling ar1.SOPControl(2)...")
        local ok, ret = pcall(function() return ar1.SOPControl(2) end)
        if ok then
            result.sop_control_return = tostring(ret)
            writeProgress("after_SOPControl", tostring(ret))
            safeLog("SOPControl(2) returned: " .. tostring(ret))
        else
            result.error = "SOPControl crashed: " .. tostring(ret)
            writeProgress("after_SOPControl", "error: " .. tostring(ret))
            return
        end
    end
"""

    if "connect" in steps:
        script += f"""
    -- Connect
    if ar1.Connect then
        result.connect_called = true
        writeProgress("before_Connect")
        safeLog("Calling ar1.Connect({com_num}, {baud}, {timeout_ms})...")
        local ok, ret = pcall(function() return ar1.Connect({com_num}, {baud}, {timeout_ms}) end)
        if ok then
            result.connect_return = tostring(ret)
            writeProgress("after_Connect", tostring(ret))
            safeLog("Connect returned: " .. tostring(ret))
        else
            result.error = "Connect crashed: " .. tostring(ret)
            writeProgress("after_Connect", "error: " .. tostring(ret))
            return
        end
    end
"""

    if "is_connected_final" in steps:
        script += """
    -- Final IsConnected
    if ar1.IsConnected then
        writeProgress("before_IsConnected_final")
        local ok, ret = pcall(function() return ar1.IsConnected() end)
        if ok then
            result.is_connected_final = tostring(ret)
        end
        writeProgress("after_IsConnected_final", tostring(ret))
    end
"""

    script += """
    writeProgress("result_written")
end

-- Clear old progress file
local pf = io.open(prog_path, "w")
if pf then pf:close() end

pcall(run)
writeResult()
"""
    return script


def write_connection_diag_script(
    out_path: Path,
    run_id: str,
    com_num: int,
    baud: int = 921600,
    timeout_ms: int = 1000,
    steps: list[str] = None,
) -> None:
    """Generate and write a diagnostic connection-only Lua script with safety validation."""
    result_dir = str(out_path.parent.resolve())
    script = build_connection_diag_script(run_id, com_num, baud, timeout_ms, result_dir, steps)

    violations = validate_script_safety(script, StageName.CONNECTION_ONLY)
    if violations:
        raise RuntimeError(
            f"SAFETY VIOLATION: Generated connection script contains forbidden calls:\\n"
            + "\\n".join(violations)
        )

    out_path.write_text(script, encoding="utf-8")


def build_smoke_script(run_id: str, result_dir: str = ".") -> str:
    """Generate a harmless smoke-test Lua script.

    This script contains NO ar1 hardware calls.  It only:
    - Calls WriteToLog via pcall (to test logging)
    - Writes smoke_result.json via io.open
    - Proves the Python -> mmWave Studio -> Lua -> JSON -> Python path works

    Wrapped in xpcall so that if anything fails, it still tries to write
    an error result JSON.
    """
    result_path = result_dir.replace("\\", "/") + "/smoke_result.json"

    return f"""\
-- Smoke Test Script
-- Generated by awr2944_dca mmws backend
-- run_id: {run_id}
-- Contains NO ar1 hardware calls.

local run_id = "{run_id}"
local out_path = "{result_path}"

local function write_result(success, log_ok, err_msg)
    local f, ferr = io.open(out_path, "w")
    if f then
        f:write('{{\\n')
        f:write('  "run_id": "' .. run_id .. '",\\n')
        f:write('  "executed": true,\\n')
        f:write('  "log_available": ' .. tostring(log_ok) .. ',\\n')
        f:write('  "write_ok": true,\\n')
        if success then
            f:write('  "error": null\\n')
        else
            f:write('  "error": "' .. tostring(err_msg):gsub('"', '\\\\"') .. '"\\n')
        end
        f:write('}}\\n')
        f:close()
    end
end

local ok, err = xpcall(function()
    local log_ok = false

    -- Test WriteToLog
    if WriteToLog then
        local wok, werr = pcall(function()
            WriteToLog("SMOKE TEST: run_id=" .. run_id .. "\\n")
        end)
        log_ok = wok
    end

    write_result(true, log_ok, nil)
end, function(e)
    return tostring(e)
end)

if not ok then
    -- xpcall error handler: try to write error result
    pcall(write_result, false, false, err)
end
"""


def write_smoke_script(out_path: Path, run_id: str) -> None:
    """Generate and write the smoke test script."""
    result_dir = str(out_path.parent.resolve())
    script = build_smoke_script(run_id, result_dir)

    # Safety: verify no ar1 calls at all
    import re
    ar1_calls = re.findall(r"ar1\.\w+", script)
    if ar1_calls:
        raise RuntimeError(
            f"SAFETY VIOLATION: Smoke script contains ar1 calls: {ar1_calls}"
        )

    out_path.write_text(script, encoding="utf-8")


# ---------------------------------------------------------------------------
# lua-launch self-contained scripts
#
# These scripts are executed via mmWaveStudio.exe /lua BEFORE Startup.lua
# finishes.  They must NOT depend on WriteToLog, writeToLog, ar1, or any
# Startup.lua helper.  All output is via io.open only.
# ---------------------------------------------------------------------------


def build_lua_launch_smoke(run_id: str, result_path: str) -> str:
    """Generate a self-contained smoke script for lua-launch.

    No WriteToLog, no ar1, no Startup.lua dependency.
    Writes result JSON via io.open only.
    """
    result_path = result_path.replace("\\", "/")
    return f"""\
-- lua-launch smoke test
-- Self-contained: no WriteToLog, no ar1, no Startup.lua
-- run_id: {run_id}

local run_id = "{run_id}"
local out_path = [[{result_path}]]

local function line(f, s)
    f:write(s)
    f:write("\\n")
end

local ok, err = pcall(function()
    local f = io.open(out_path, "w")
    if not f then
        error("Cannot open result file: " .. out_path)
    end
    line(f, "{{")
    line(f, '  "run_id": "' .. run_id .. '",')
    line(f, '  "executed": true,')
    line(f, '  "write_ok": true,')
    line(f, '  "error": null')
    line(f, "}}")
    f:close()
end)

if not ok then
    -- Last-ditch: try to write error result
    local f = io.open(out_path, "w")
    if f then
        line(f, "{{")
        line(f, '  "run_id": "' .. run_id .. '",')
        line(f, '  "executed": false,')
        line(f, '  "write_ok": false,')
        line(f, '  "error": "' .. tostring(err):gsub('"', '\\\\"') .. '"')
        line(f, "}}")
        f:close()
    end
end
"""


def build_lua_launch_env_probe(run_id: str, result_path: str) -> str:
    """Generate a self-contained environment probe for lua-launch.

    Reports minimal fields:
      run_id, executed, _VERSION, type_ar1, ar1_connect_exists,
      type_WriteToLog, type_writeToLog, io_open_works.
    """
    result_path = result_path.replace("\\", "/")
    # The esc() function must escape in this order:
    #   1. backslash -> \\   (must be first!)
    #   2. quote -> \"
    #   3. newline -> \\n
    #   4. carriage return -> \\r
    #   5. tab -> \\t
    # In the f-string, Lua sees the literal gsub patterns.
    return f"""\
-- lua-launch env-probe
-- Self-contained: no WriteToLog, no ar1, no Startup.lua
-- run_id: {run_id}

local run_id = "{run_id}"
local out_path = [[{result_path}]]

local function esc(s)
    if s == nil then return "null" end
    s = tostring(s)
    s = s:gsub("\\\\", "\\\\\\\\")
    s = s:gsub('"', '\\\\"')
    s = s:gsub("\\r", "\\\\r")
    s = s:gsub("\\n", "\\\\n")
    s = s:gsub("\\t", "\\\\t")
    return '"' .. s .. '"'
end

local function line(f, s)
    f:write(s)
    f:write("\\n")
end

local ok, err = pcall(function()
    local lua_version = _VERSION or "unknown"
    local ar1_type = type(ar1)
    local ar1_connect_exists = false
    if type(ar1) == "table" and ar1.Connect then
        ar1_connect_exists = true
    end
    local write_to_log_type = type(WriteToLog)
    local write_to_log_lower_type = type(writeToLog)

    local f = io.open(out_path, "w")
    if not f then
        error("Cannot open result file: " .. out_path)
    end
    
    line(f, "{{")
    line(f, '  "run_id": ' .. esc(run_id) .. ',')
    line(f, '  "executed": true,')
    line(f, '  "_VERSION": ' .. esc(lua_version) .. ',')
    line(f, '  "type_ar1": ' .. esc(ar1_type) .. ',')
    line(f, '  "ar1_connect_exists": ' .. tostring(ar1_connect_exists) .. ',')
    line(f, '  "type_WriteToLog": ' .. esc(write_to_log_type) .. ',')
    line(f, '  "type_writeToLog": ' .. esc(write_to_log_lower_type) .. ',')
    line(f, '  "io_open_works": true,')
    line(f, '  "error": null')
    line(f, "}}")
    f:close()
end)

if not ok then
    local f = io.open(out_path, "w")
    if f then
        line(f, "{{")
        line(f, '  "run_id": ' .. esc(run_id) .. ',')
        line(f, '  "executed": false,')
        line(f, '  "error": ' .. esc(tostring(err)))
        line(f, "}}")
        f:close()
    end
end
"""


def build_lua_launch_startup_probe(run_id: str, result_path: str, startup_lua_path: str) -> str:
    """Generate a probe script that explicitly invokes Startup.lua and measures its effect."""
    result_path = result_path.replace("\\", "/")
    startup_lua_path = startup_lua_path.replace("\\", "/")
    return f"""\
-- lua-launch startup-probe
-- run_id: {run_id}

local run_id = "{run_id}"
local out_path = [[{result_path}]]
local startup_path = [[{startup_lua_path}]]

local function esc(s)
    if s == nil then return "null" end
    s = tostring(s)
    s = s:gsub("\\\\", "\\\\\\\\")
    s = s:gsub('"', '\\\\"')
    s = s:gsub("\\r", "\\\\r")
    s = s:gsub("\\n", "\\\\n")
    s = s:gsub("\\t", "\\\\t")
    return '"' .. s .. '"'
end

local function line(f, s)
    f:write(s)
    f:write("\\n")
end

local function check_state(prefix)
    local state = {{}}
    state[prefix .. "_type_ar1"] = type(ar1)
    state[prefix .. "_ar1_connect_exists"] = false
    if type(ar1) == "table" and ar1.Connect then
        state[prefix .. "_ar1_connect_exists"] = true
    end
    state[prefix .. "_type_WriteToLog"] = type(WriteToLog)
    state[prefix .. "_type_writeToLog"] = type(writeToLog)
    state[prefix .. "_type_RSTD"] = type(RSTD)
    return state
end

local ok, err = pcall(function()
    local f = io.open(out_path, "w")
    if not f then error("Cannot open result file") end
    
    local before = check_state("before")
    
    local startup_ok, startup_err = pcall(function()
        dofile(startup_path)
    end)
    
    local after = check_state("after")
    
    line(f, "{{")
    line(f, '  "run_id": ' .. esc(run_id) .. ',')
    line(f, '  "executed": true,')
    line(f, '  "startup_ok": ' .. tostring(startup_ok) .. ',')
    if not startup_ok then
        line(f, '  "startup_err": ' .. esc(startup_err) .. ',')
    else
        line(f, '  "startup_err": null,')
    end
    for k, v in pairs(before) do
        if type(v) == "boolean" then
            line(f, '  "' .. k .. '": ' .. tostring(v) .. ',')
        else
            line(f, '  "' .. k .. '": ' .. esc(v) .. ',')
        end
    end
    local count = 0
    for k, v in pairs(after) do
        count = count + 1
        local comma = count < 5 and "," or ""
        if type(v) == "boolean" then
            line(f, '  "' .. k .. '": ' .. tostring(v) .. comma)
        else
            line(f, '  "' .. k .. '": ' .. esc(v) .. comma)
        end
    end
    line(f, "}}")
    f:close()
end)

if not ok then
    local f = io.open(out_path, "w")
    if f then
        line(f, "{{")
        line(f, '  "run_id": ' .. esc(run_id) .. ',')
        line(f, '  "executed": false,')
        line(f, '  "error": ' .. esc(tostring(err)))
        line(f, "}}")
        f:close()
    end
end
"""


def build_lua_launch_wait_env_probe(run_id: str, result_path: str, poll_interval_ms: int = 500, max_duration_s: int = 20) -> str:
    """Generate a probe script that polls the environment to see if variables appear."""
    result_path = result_path.replace("\\", "/")
    return f"""\
-- lua-launch wait-env-probe
-- run_id: {run_id}

local run_id = "{run_id}"
local out_path = [[{result_path}]]
local jsonl_path = out_path .. ".jsonl"

local function esc(s)
    if s == nil then return "null" end
    s = tostring(s)
    s = s:gsub("\\\\", "\\\\\\\\")
    s = s:gsub('"', '\\\\"')
    s = s:gsub("\\r", "\\\\r")
    s = s:gsub("\\n", "\\\\n")
    s = s:gsub("\\t", "\\\\t")
    return '"' .. s .. '"'
end

local function line(f, s)
    f:write(s)
    f:write("\\n")
end

local function sleep(s)
    local ntime = os.clock() + s
    repeat until os.clock() > ntime
end

local ok, err = pcall(function()
    local lf = io.open(jsonl_path, "w")
    if lf then lf:close() end

    local start_time = os.clock()
    local max_time = start_time + {max_duration_s}
    
    local final_ar1_type = "nil"
    
    while os.clock() < max_time do
        local elapsed = os.clock() - start_time
        
        local ar1_type = type(ar1)
        local ar1_connect_exists = false
        if type(ar1) == "table" and ar1.Connect then
            ar1_connect_exists = true
        end
        local write_to_log_type = type(WriteToLog)
        
        lf = io.open(jsonl_path, "a")
        if lf then
            line(lf, '{{"elapsed": ' .. tostring(elapsed) .. ', "type_ar1": ' .. esc(ar1_type) .. ', "ar1_connect_exists": ' .. tostring(ar1_connect_exists) .. ', "type_WriteToLog": ' .. esc(write_to_log_type) .. '}}')
            lf:close()
        end
        
        if ar1_type == "table" and ar1_connect_exists then
            final_ar1_type = "table"
            break
        end
        
        sleep({poll_interval_ms} / 1000.0)
    end
    
    local f = io.open(out_path, "w")
    if not f then error("Cannot open result file") end
    
    line(f, "{{")
    line(f, '  "run_id": ' .. esc(run_id) .. ',')
    line(f, '  "executed": true,')
    line(f, '  "final_ar1_type": ' .. esc(final_ar1_type) .. ',')
    line(f, '  "timeout": ' .. tostring(os.clock() >= max_time))
    line(f, "}}")
    f:close()
end)

if not ok then
    local f = io.open(out_path, "w")
    if f then
        line(f, "{{")
        line(f, '  "run_id": ' .. esc(run_id) .. ',')
        line(f, '  "executed": false,')
        line(f, '  "error": ' .. esc(tostring(err)))
        line(f, "}}")
        f:close()
    end
end
"""


def build_lua_launch_rstd_env_probe(run_id: str, result_path: str) -> str:
    result_path = result_path.replace("\\", "/")
    return f"""\
-- lua-launch rstd-env-probe
local run_id = "{run_id}"
local out_path = [[{result_path}]]

local function esc(s)
    if s == nil then return "null" end
    s = tostring(s)
    s = s:gsub("\\\\", "\\\\\\\\")
    s = s:gsub('"', '\\\\"')
    s = s:gsub("\\r", "\\\\r")
    s = s:gsub("\\n", "\\\\n")
    s = s:gsub("\\t", "\\\\t")
    return '"' .. s .. '"'
end
local function line(f, s) f:write(s); f:write("\\n") end

local ok, err = pcall(function()
    local type_rstd = type(RSTD)
    local has_registerdllex = false
    local has_netstart = false
    if type_rstd == "table" then
        if type(RSTD.RegisterDllEx) == "function" or type(RSTD.RegisterDllEx) == "userdata" then has_registerdllex = true end
        if type(RSTD.NetStart) == "function" or type(RSTD.NetStart) == "userdata" then has_netstart = true end
    end
    
    local f = io.open(out_path, "w")
    if not f then error("Cannot open result file") end
    
    line(f, "{{")
    line(f, '  "run_id": ' .. esc(run_id) .. ',')
    line(f, '  "executed": true,')
    line(f, '  "type_RSTD": ' .. esc(type_rstd) .. ',')
    line(f, '  "RSTD_RegisterDllEx_exists": ' .. tostring(has_registerdllex) .. ',')
    line(f, '  "RSTD_NetStart_exists": ' .. tostring(has_netstart) .. ',')
    line(f, '  "type_ar1": ' .. esc(type(ar1)) .. ',')
    line(f, '  "type_WriteToLog": ' .. esc(type(WriteToLog)) .. ',')
    line(f, '  "type_writeToLog": ' .. esc(type(writeToLog)))
    line(f, "}}")
    f:close()
end)
if not ok then
    local f = io.open(out_path, "w")
    if f then
        line(f, "{{")
        line(f, '  "run_id": ' .. esc(run_id) .. ',')
        line(f, '  "executed": false,')
        line(f, '  "error": ' .. esc(tostring(err)))
        line(f, "}}")
        f:close()
    end
end
"""

def build_lua_launch_registerdll_probe(run_id: str, result_path: str) -> str:
    result_path = result_path.replace("\\", "/")
    return f"""\
-- lua-launch registerdll-probe
local run_id = "{run_id}"
local out_path = [[{result_path}]]
local jsonl_path = out_path .. ".jsonl"

local function esc(s)
    if s == nil then return "null" end
    s = tostring(s)
    s = s:gsub("\\\\", "\\\\\\\\")
    s = s:gsub('"', '\\\\"')
    s = s:gsub("\\r", "\\\\r")
    s = s:gsub("\\n", "\\\\n")
    s = s:gsub("\\t", "\\\\t")
    return '"' .. s .. '"'
end
local function line(f, s) f:write(s); f:write("\\n") end

local ok, err = pcall(function()
    local lf = io.open(jsonl_path, "w")
    if lf then 
        line(lf, '{{\"step\": \"start\", \"type_RSTD\": ' .. esc(type(RSTD)) .. '}}')
        lf:close()
    end

    local type_RSTD = type(RSTD)
    local register_ok, register_err = false, "RSTD not found"
    if type_RSTD == "table" and RSTD.GetRstdPath then
        local rstd_path = RSTD.GetRstdPath()
        local ar1x_controller_path = rstd_path .. "\\\\Clients\\\\AR1xController\\\\AR1xController.dll"
        register_ok, register_err = pcall(function()
            RSTD.RegisterDllEx(ar1x_controller_path, false)
        end)
    end
    
    lf = io.open(jsonl_path, "a")
    if lf then 
        line(lf, '{{\"step\": \"after_register\", \"ok\": ' .. tostring(register_ok) .. ', \"err\": ' .. esc(register_err) .. '}}')
        lf:close()
    end
    
    local ar1_type = type(ar1)
    local ar1_connect_exists = false
    local ar1_isconnected_exists = false
    local ar1_sopcontrol_exists = false
    if ar1_type == "table" then
        ar1_connect_exists = (ar1.Connect ~= nil)
        ar1_isconnected_exists = (ar1.IsConnected ~= nil)
        ar1_sopcontrol_exists = (ar1.SOPControl ~= nil)
    end
    
    local f = io.open(out_path, "w")
    if not f then error("Cannot open result file") end
    
    line(f, "{{")
    line(f, '  "run_id": ' .. esc(run_id) .. ',')
    line(f, '  "executed": true,')
    line(f, '  "type_RSTD": ' .. esc(type_RSTD) .. ',')
    line(f, '  "register_ok": ' .. tostring(register_ok) .. ',')
    line(f, '  "register_err": ' .. esc(register_err) .. ',')
    line(f, '  "type_ar1": ' .. esc(ar1_type) .. ',')
    line(f, '  "ar1_connect_exists": ' .. tostring(ar1_connect_exists) .. ',')
    line(f, '  "ar1_isconnected_exists": ' .. tostring(ar1_isconnected_exists) .. ',')
    line(f, '  "ar1_sopcontrol_exists": ' .. tostring(ar1_sopcontrol_exists))
    line(f, "}}")
    f:close()
end)
if not ok then
    local f = io.open(out_path, "w")
    if f then
        line(f, "{{")
        line(f, '  "run_id": ' .. esc(run_id) .. ',')
        line(f, '  "executed": false,')
        line(f, '  "error": ' .. esc(tostring(err)))
        line(f, "}}")
        f:close()
    end
end
"""

def build_lua_launch_startup_lite_probe(run_id: str, result_path: str) -> str:
    result_path = result_path.replace("\\", "/")
    return f"""\
-- lua-launch startup-lite-probe
local run_id = "{run_id}"
local out_path = [[{result_path}]]

local function esc(s)
    if s == nil then return "null" end
    s = tostring(s)
    s = s:gsub("\\\\", "\\\\\\\\")
    s = s:gsub('"', '\\\\"')
    s = s:gsub("\\r", "\\\\r")
    s = s:gsub("\\n", "\\\\n")
    s = s:gsub("\\t", "\\\\t")
    return '"' .. s .. '"'
end
local function line(f, s) f:write(s); f:write("\\n") end

local ok, err = pcall(function()
    local RSTD_PATH = "C:\\\\ti\\\\mmwave_studio_03_01_04_04\\\\mmWaveStudio"
    if type(RSTD) == "table" and RSTD.GetRstdPath then RSTD_PATH = RSTD.GetRstdPath() end
    
    local ar1x_controller_path = RSTD_PATH .. "\\\\Clients\\\\AR1xController\\\\AR1xController.dll"
    local registers_xml = RSTD_PATH .. "\\\\Clients\\\\AR1xController\\\\AR2944ES1P0_Registers.xml"
    local al_path = RSTD_PATH .. "\\\\RunTime\\\\SAL.dll"
    local client_path = RSTD_PATH .. "\\\\Clients\\\\LabClient.dll"
    
    if type(RSTD) == "table" and RSTD.UnBuild then
        RSTD.UnBuild()
        RSTD.SetClientDll(al_path, client_path, "", 0)
        
        RSTD.SetVar("/Settings/AutoUpdate/Enabled", "TRUE")
        RSTD.SetVar("/Settings/AutoUpdate/Interval", "1")
        RSTD.SetVar("/Settings/Monitors/UpdateDisplay", "TRUE")
        RSTD.SetVar("/Settings/Monitors/OneClickStart", "TRUE")
        RSTD.SetVar("/Settings/Automation/Automation Mode", "false")
        RSTD.Transmit("/")
        RSTD.SaveClientSettings()
        
        pcall(function() dofile(RSTD_PATH .. "\\\\Scripts\\\\Startup\\\\General_functions.lua") end)
        pcall(function() dofile(RSTD_PATH .. "\\\\Scripts\\\\Startup\\\\BinDecHex.lua") end)
        pcall(function() dofile(RSTD_PATH .. "\\\\Scripts\\\\Startup\\\\lib_math.lua") end)
        
        RSTD.Build()
    end
    
    local reg_ok, reg_err = false, "RSTD not table"
    if type(RSTD) == "table" and RSTD.RegisterDllEx then
        reg_ok, reg_err = pcall(function()
            RSTD.RegisterDllEx(ar1x_controller_path, false)
            RSTD.SetExternalAL(ar1x_controller_path)
            RSTD.SetTitle("Startup-Lite")
            RSTD.LoadExpose(registers_xml)
        end)
    end
    
    local f = io.open(out_path, "w")
    if not f then error("Cannot open result file") end
    
    line(f, "{{")
    line(f, '  "run_id": ' .. esc(run_id) .. ',')
    line(f, '  "executed": true,')
    line(f, '  "lite_ok": ' .. tostring(reg_ok) .. ',')
    line(f, '  "lite_err": ' .. esc(reg_err) .. ',')
    line(f, '  "type_ar1": ' .. esc(type(ar1)))
    line(f, "}}")
    f:close()
end)
if not ok then
    local f = io.open(out_path, "w")
    if f then
        line(f, "{{")
        line(f, '  "run_id": ' .. esc(run_id) .. ',')
        line(f, '  "executed": false,')
        line(f, '  "error": ' .. esc(tostring(err)))
        line(f, "}}")
        f:close()
    end
end
"""


# ---------------------------------------------------------------------------
# Shared startup-lite Lua snippet (embedded inline into compound scripts)
# ---------------------------------------------------------------------------

_STARTUP_LITE_SNIPPET = r"""
local RSTD_PATH = "C:\\ti\\mmwave_studio_03_01_04_04\\mmWaveStudio"
if type(RSTD) == "table" and RSTD.GetRstdPath then RSTD_PATH = RSTD.GetRstdPath() end

-- Critical alias from Startup.lua line 4: RTTT = RSTD
-- AR1xController internals (ShowGui, Connect, etc.) reference RTTT
if type(RSTD) == "table" then
    RTTT = RSTD
end

local ar1x_controller_path = RSTD_PATH .. "\\Clients\\AR1xController\\AR1xController.dll"
local registers_xml = RSTD_PATH .. "\\Clients\\AR1xController\\AR2944ES1P0_Registers.xml"
local al_path = RSTD_PATH .. "\\RunTime\\SAL.dll"
local client_path = RSTD_PATH .. "\\Clients\\LabClient.dll"

if type(RSTD) ~= "table" or not RSTD.UnBuild then
    error("STARTUP_LITE_FAILED: RSTD not available")
end

RSTD.UnBuild()
RSTD.SetClientDll(al_path, client_path, "", 0)

RSTD.SetVar("/Settings/AutoUpdate/Enabled", "TRUE")
RSTD.SetVar("/Settings/AutoUpdate/Interval", "1")
RSTD.SetVar("/Settings/Monitors/UpdateDisplay", "TRUE")
RSTD.SetVar("/Settings/Monitors/OneClickStart", "TRUE")
RSTD.SetVar("/Settings/Automation/Automation Mode", "false")
RSTD.Transmit("/")
RSTD.SaveClientSettings()

pcall(function() dofile(RSTD_PATH .. "\\Scripts\\Startup\\General_functions.lua") end)
pcall(function() dofile(RSTD_PATH .. "\\Scripts\\Startup\\BinDecHex.lua") end)
pcall(function() dofile(RSTD_PATH .. "\\Scripts\\Startup\\lib_math.lua") end)

RSTD.Build()

RSTD.RegisterDllEx(ar1x_controller_path, false)
RSTD.SetExternalAL(ar1x_controller_path)
RSTD.SetTitle("AWR-CLI")
RSTD.LoadExpose(registers_xml)
"""


# ---------------------------------------------------------------------------
# Startup-lite V3: exact reproduction of Startup.lua non-blocking lines
# ---------------------------------------------------------------------------

_STARTUP_LITE_V3_SNIPPET = r"""
local RSTD_PATH = "C:\\ti\\mmwave_studio_03_01_04_04\\mmWaveStudio"
if type(RSTD) == "table" and RSTD.GetRstdPath then RSTD_PATH = RSTD.GetRstdPath() end

-- Startup.lua line 4: RTTT = RSTD (critical alias used by AR1xController)
if type(RSTD) == "table" then
    RTTT = RSTD
end

-- Startup.lua line 16: AR1_GUI = true
AR1_GUI = true

-- Setup package.path to match normal GUI environment
local runtime_path = RSTD_PATH .. "\\RunTime"
package.path = ".\\?.lua;"
    .. runtime_path .. "\\lua\\?.lua;"
    .. runtime_path .. "\\lua\\?\\init.lua;"
    .. runtime_path .. "\\?.lua;"
    .. runtime_path .. "\\?\\init.lua;"
    .. runtime_path .. "\\LuaScripts\\?.lua;"
    .. runtime_path .. "\\..\\Clients\\LuaModules\\LuaSocket\\?.lua"

local ar1x_controller_path = RSTD_PATH .. "\\Clients\\AR1xController\\AR1xController.dll"
local registers_xml = RSTD_PATH .. "\\Clients\\AR1xController\\AR2944ES1P0_Registers.xml"
local al_path = RSTD_PATH .. "\\RunTime\\SAL.dll"
local client_path = RSTD_PATH .. "\\Clients\\LabClient.dll"

if type(RSTD) ~= "table" or not RSTD.UnBuild then
    error("STARTUP_LITE_V3_FAILED: RSTD not available")
end

RSTD.UnBuild()
RSTD.SetClientDll(al_path, client_path, "", 0)

RSTD.SetVar("/Settings/AutoUpdate/Enabled", "TRUE")
RSTD.SetVar("/Settings/AutoUpdate/Interval", "1")
RSTD.SetVar("/Settings/Monitors/UpdateDisplay", "TRUE")
RSTD.SetVar("/Settings/Monitors/OneClickStart", "TRUE")
RSTD.SetVar("/Settings/Automation/Automation Mode", "false")
RSTD.Transmit("/")
RSTD.SaveClientSettings()

RSTD.SetAndTransmit("/Settings/Scripter/Display DateTime", "1")
RSTD.SetAndTransmit("/Settings/Scripter/DateTime Format", "HH:mm:ss")

pcall(function() dofile(RSTD_PATH .. "\\Scripts\\Startup\\General_functions.lua") end)
pcall(function() dofile(RSTD_PATH .. "\\Scripts\\Startup\\BinDecHex.lua") end)
pcall(function() dofile(RSTD_PATH .. "\\Scripts\\Startup\\lib_math.lua") end)

RSTD.Build()

RSTD.RegisterDllEx(ar1x_controller_path, false)
RSTD.SetExternalAL(ar1x_controller_path)

-- Startup.lua line 66: RSTD.SetTitle(ar1.GuiVersion())
local gv_ok, gv_ret = pcall(function() return ar1.GuiVersion() end)
if gv_ok and gv_ret then
    RSTD.SetTitle(tostring(gv_ret))
else
    RSTD.SetTitle("AWR-CLI")
end

RSTD.LoadExpose(registers_xml)
"""


def _v3_snippet_escaped() -> str:
    """Return the v3 snippet with backslashes doubled for f-string embedding."""
    return _STARTUP_LITE_V3_SNIPPET.replace("\\", "\\\\")


def build_lua_launch_startup_lite_v3_probe(
    run_id: str, result_path: str, jsonl_path: str,
) -> str:
    """Probe that runs startup-lite-v3 with granular progress at every step."""
    result_path = result_path.replace("\\", "/")
    jsonl_path = jsonl_path.replace("\\", "/")
    snippet = _v3_snippet_escaped()
    return f"""\
local run_id = "{run_id}"
local out_path = [[{result_path}]]
local jsonl_path = [[{jsonl_path}]]

local function esc(s)
    if s == nil then return "null" end
    s = tostring(s)
    s = s:gsub("\\\\", "\\\\\\\\")
    s = s:gsub('"', '\\\\"')
    s = s:gsub("\\r", "\\\\r")
    s = s:gsub("\\n", "\\\\n")
    s = s:gsub("\\t", "\\\\t")
    return '"' .. s .. '"'
end
local function line(f, s) f:write(s); f:write("\\n") end
local function progress(step, detail)
    local lf = io.open(jsonl_path, "a")
    if lf then
        if detail then
            line(lf, '{{"step": ' .. esc(step) .. ', "detail": ' .. esc(detail) .. '}}')
        else
            line(lf, '{{"step": ' .. esc(step) .. '}}')
        end
        lf:close()
    end
end

local status = "NO_START"
local gv_ret = nil

local ok, err = pcall(function()
    local lf = io.open(jsonl_path, "w"); if lf then lf:close() end
    progress("script_started")

    local RSTD_PATH = RSTD.GetRstdPath()
    progress("rstd_path", RSTD_PATH)

    progress("before_RTTT_alias")
    if type(RSTD) == "table" then RTTT = RSTD end
    progress("after_RTTT_alias", "type(RTTT)=" .. type(RTTT))

    progress("before_AR1_GUI")
    AR1_GUI = true
    progress("after_AR1_GUI", tostring(AR1_GUI))

    local runtime_path = RSTD_PATH .. "\\\\RunTime"
    package.path = ".\\\\?.lua;"
        .. runtime_path .. "\\\\lua\\\\?.lua;"
        .. runtime_path .. "\\\\lua\\\\?\\\\init.lua;"
        .. runtime_path .. "\\\\?.lua;"
        .. runtime_path .. "\\\\?\\\\init.lua;"
        .. runtime_path .. "\\\\LuaScripts\\\\?.lua;"
        .. runtime_path .. "\\\\..\\\\Clients\\\\LuaModules\\\\LuaSocket\\\\?.lua"
    progress("package_path_set", package.path)

    local ar1x_controller_path = RSTD_PATH .. "\\\\Clients\\\\AR1xController\\\\AR1xController.dll"
    local registers_xml = RSTD_PATH .. "\\\\Clients\\\\AR1xController\\\\AR2944ES1P0_Registers.xml"
    local al_path = RSTD_PATH .. "\\\\RunTime\\\\SAL.dll"
    local client_path = RSTD_PATH .. "\\\\Clients\\\\LabClient.dll"

    RSTD.UnBuild()
    RSTD.SetClientDll(al_path, client_path, "", 0)
    RSTD.SetVar("/Settings/AutoUpdate/Enabled", "TRUE")
    RSTD.SetVar("/Settings/AutoUpdate/Interval", "1")
    RSTD.SetVar("/Settings/Monitors/UpdateDisplay", "TRUE")
    RSTD.SetVar("/Settings/Monitors/OneClickStart", "TRUE")
    RSTD.SetVar("/Settings/Automation/Automation Mode", "false")
    RSTD.Transmit("/")
    RSTD.SaveClientSettings()
    RSTD.SetAndTransmit("/Settings/Scripter/Display DateTime", "1")
    RSTD.SetAndTransmit("/Settings/Scripter/DateTime Format", "HH:mm:ss")

    pcall(function() dofile(RSTD_PATH .. "\\\\Scripts\\\\Startup\\\\General_functions.lua") end)
    pcall(function() dofile(RSTD_PATH .. "\\\\Scripts\\\\Startup\\\\BinDecHex.lua") end)
    pcall(function() dofile(RSTD_PATH .. "\\\\Scripts\\\\Startup\\\\lib_math.lua") end)

    progress("before_Build")
    RSTD.Build()
    progress("after_Build")

    progress("before_RegisterDllEx")
    RSTD.RegisterDllEx(ar1x_controller_path, false)
    RSTD.SetExternalAL(ar1x_controller_path)
    progress("after_RegisterDllEx", "type(ar1)=" .. type(ar1))

    progress("before_GuiVersion")
    local gv_ok2
    gv_ok2, gv_ret = pcall(function() return ar1.GuiVersion() end)
    progress("after_GuiVersion", tostring(gv_ok2) .. " " .. tostring(gv_ret))
    if gv_ok2 and gv_ret then
        RSTD.SetTitle(tostring(gv_ret))
    else
        RSTD.SetTitle("AWR-CLI")
    end

    progress("before_LoadExpose")
    RSTD.LoadExpose(registers_xml)
    progress("after_LoadExpose")

    status = "STARTUP_LITE_V3_OK"

    local f = io.open(out_path, "w")
    if f then
        line(f, "{{")
        line(f, '  "run_id": ' .. esc(run_id) .. ',')
        line(f, '  "executed": true,')
        line(f, '  "status": ' .. esc(status) .. ',')
        line(f, '  "type_ar1": ' .. esc(type(ar1)) .. ',')
        line(f, '  "type_RTTT": ' .. esc(type(RTTT)) .. ',')
        line(f, '  "AR1_GUI": ' .. tostring(AR1_GUI) .. ',')
        line(f, '  "gui_version": ' .. esc(gv_ret) .. ',')
        line(f, '  "error": null')
        line(f, "}}")
        f:close()
    end
end)

if not ok then
    local f = io.open(out_path, "w")
    if f then
        line(f, "{{")
        line(f, '  "run_id": ' .. esc(run_id) .. ',')
        line(f, '  "executed": false,')
        line(f, '  "status": ' .. esc(status) .. ',')
        line(f, '  "error": ' .. esc(tostring(err)))
        line(f, "}}")
        f:close()
    end
end
"""


def build_lua_launch_path_env_probe(
    run_id: str, result_path: str, jsonl_path: str,
) -> str:
    """Dump environment paths before and after startup-lite-v3."""
    result_path = result_path.replace("\\", "/")
    jsonl_path = jsonl_path.replace("\\", "/")
    snippet_v3 = _v3_snippet_escaped()
    return f"""\
local run_id = "{run_id}"
local out_path = [[{result_path}]]
local jsonl_path = [[{jsonl_path}]]

local function esc(s)
    if s == nil then return "null" end
    s = tostring(s)
    s = s:gsub("\\\\", "\\\\\\\\")
    s = s:gsub('"', '\\\\"')
    s = s:gsub("\\r", "\\\\r")
    s = s:gsub("\\n", "\\\\n")
    s = s:gsub("\\t", "\\\\t")
    return '"' .. s .. '"'
end
local function line(f, s) f:write(s); f:write("\\n") end
local function progress(step, detail)
    local lf = io.open(jsonl_path, "a")
    if lf then
        if detail then
            line(lf, '{{"step": ' .. esc(step) .. ', "detail": ' .. esc(detail) .. '}}')
        else
            line(lf, '{{"step": ' .. esc(step) .. '}}')
        end
        lf:close()
    end
end

local function safe_call(fn)
    local ok2, ret = pcall(fn)
    if ok2 then return tostring(ret) else return "ERROR: " .. tostring(ret) end
end

local ok, err = pcall(function()
    local lf = io.open(jsonl_path, "w"); if lf then lf:close() end
    progress("script_started")

    progress("pre_init_snapshot")
    progress("pre_GetRstdPath", safe_call(function() return RSTD.GetRstdPath() end))
    progress("pre_GetApplicationDir", safe_call(function() return RSTD.GetApplicationDir() end))
    progress("pre_GetWorkingDirectory", safe_call(function() return RSTD.GetWorkingDirectory() end))
    progress("pre_GetSettingsPath", safe_call(function() return RSTD.GetSettingsPath() end))
    progress("pre_package_path", package.path or "nil")
    progress("pre_types", "RSTD=" .. type(RSTD) .. " RTTT=" .. type(RTTT) .. " ar1=" .. type(ar1) .. " AR1_GUI=" .. type(AR1_GUI) .. " val=" .. tostring(AR1_GUI))

    progress("before_startup_lite_v3")
    local lite_ok, lite_err = pcall(function()
{snippet_v3}
    end)
    progress("after_startup_lite_v3", tostring(lite_ok) .. " " .. tostring(lite_err))

    progress("post_init_snapshot")
    progress("post_GetRstdPath", safe_call(function() return RSTD.GetRstdPath() end))
    progress("post_GetApplicationDir", safe_call(function() return RSTD.GetApplicationDir() end))
    progress("post_GetWorkingDirectory", safe_call(function() return RSTD.GetWorkingDirectory() end))
    progress("post_GetSettingsPath", safe_call(function() return RSTD.GetSettingsPath() end))
    progress("post_package_path", package.path or "nil")
    progress("post_types", "RSTD=" .. type(RSTD) .. " RTTT=" .. type(RTTT) .. " ar1=" .. type(ar1) .. " AR1_GUI=" .. type(AR1_GUI) .. " val=" .. tostring(AR1_GUI))

    local f = io.open(out_path, "w")
    if f then
        line(f, "{{")
        line(f, '  "run_id": ' .. esc(run_id) .. ',')
        line(f, '  "executed": true,')
        line(f, '  "startup_lite_v3_ok": ' .. tostring(lite_ok) .. ',')
        line(f, '  "type_RSTD": ' .. esc(type(RSTD)) .. ',')
        line(f, '  "type_RTTT": ' .. esc(type(RTTT)) .. ',')
        line(f, '  "type_ar1": ' .. esc(type(ar1)) .. ',')
        line(f, '  "AR1_GUI": ' .. tostring(AR1_GUI) .. ',')
        line(f, '  "package_path": ' .. esc(package.path) .. ',')
        line(f, '  "error": null')
        line(f, "}}")
        f:close()
    end
end)

if not ok then
    local f = io.open(out_path, "w")
    if f then
        line(f, "{{")
        line(f, '  "run_id": ' .. esc(run_id) .. ',')
        line(f, '  "executed": false,')
        line(f, '  "error": ' .. esc(tostring(err)))
        line(f, "}}")
        f:close()
    end
end
"""


def build_lua_launch_radarapi_v3_connect_probe(
    run_id: str, result_path: str, jsonl_path: str,
    com_num: int, baud: int, show_gui: bool = False,
) -> str:
    """Startup-lite-v3 + optional ShowGui + ar1.Connect."""
    result_path = result_path.replace("\\", "/")
    jsonl_path = jsonl_path.replace("\\", "/")
    snippet_v3 = _v3_snippet_escaped()
    showgui_block = ""
    if show_gui:
        showgui_block = """
    progress("before_ShowGui")
    local sg_ok, sg_err = pcall(function() ar1.ShowGui() end)
    progress("after_ShowGui", tostring(sg_ok) .. " " .. tostring(sg_err))
    if not sg_ok then status = "SHOWGUI_FAILED"; error("SHOWGUI_FAILED: " .. tostring(sg_err)) end
"""
    return f"""\
local run_id = "{run_id}"
local out_path = [[{result_path}]]
local jsonl_path = [[{jsonl_path}]]

local function esc(s)
    if s == nil then return "null" end
    s = tostring(s)
    s = s:gsub("\\\\", "\\\\\\\\")
    s = s:gsub('"', '\\\\"')
    s = s:gsub("\\r", "\\\\r")
    s = s:gsub("\\n", "\\\\n")
    s = s:gsub("\\t", "\\\\t")
    return '"' .. s .. '"'
end
local function line(f, s) f:write(s); f:write("\\n") end
local function progress(step, detail)
    local lf = io.open(jsonl_path, "a")
    if lf then
        if detail then
            line(lf, '{{"step": ' .. esc(step) .. ', "detail": ' .. esc(detail) .. '}}')
        else
            line(lf, '{{"step": ' .. esc(step) .. '}}')
        end
        lf:close()
    end
end

local status = "NO_START"
local c_ret_str = "null"

local ok, err = pcall(function()
    local lf = io.open(jsonl_path, "w"); if lf then lf:close() end
    progress("script_started")

    progress("before_startup_lite_v3")
    local lite_ok, lite_err = pcall(function()
{snippet_v3}
    end)
    progress("after_startup_lite_v3", tostring(lite_ok) .. " " .. tostring(lite_err))
    if not lite_ok then status = "STARTUP_LITE_V3_FAILED"; error("STARTUP_LITE_V3_FAILED") end

    progress("check_ar1_type", type(ar1))
    if type(ar1) ~= "table" then
        status = "AR1_MISSING"
        error("AR1_MISSING")
    end
{showgui_block}
    progress("before_Connect", "COM{com_num} baud={baud} timeout=1000")
    local c_ok, c_ret = pcall(function() return ar1.Connect({com_num}, {baud}, 1000) end)

    if not c_ok then
        status = "CONNECT_EXCEPTION"
        progress("after_Connect", "ERROR: " .. tostring(c_ret))
        error("CONNECT_EXCEPTION: " .. tostring(c_ret))
    end

    progress("after_Connect", tostring(c_ret))
    c_ret_str = esc(c_ret)

    if c_ret == 0 then
        status = "CONNECT_SUCCESS"
    else
        status = "CONNECT_RETURNED_ERROR"
    end

    local f = io.open(out_path, "w")
    if f then
        line(f, "{{")
        line(f, '  "run_id": ' .. esc(run_id) .. ',')
        line(f, '  "executed": true,')
        line(f, '  "status": ' .. esc(status) .. ',')
        line(f, '  "connect_return": ' .. c_ret_str .. ',')
        line(f, '  "error": null')
        line(f, "}}")
        f:close()
    end
end)

if not ok then
    local f = io.open(out_path, "w")
    if f then
        line(f, "{{")
        line(f, '  "run_id": ' .. esc(run_id) .. ',')
        line(f, '  "executed": false,')
        line(f, '  "status": ' .. esc(status) .. ',')
        line(f, '  "error": ' .. esc(tostring(err)))
        line(f, "}}")
        f:close()
    end
end
"""


def build_lua_launch_ar1_readonly_probe(run_id: str, result_path: str, jsonl_path: str, mode: str = "method-only") -> str:
    """Generate a probe that runs startup-lite then does read-only ar1 checks.
    mode can be "method-only" or "isconnected-call".
    """
    result_path = result_path.replace("\\", "/")
    jsonl_path = jsonl_path.replace("\\", "/")
    snippet = _STARTUP_LITE_SNIPPET.replace("\\", "\\\\")
    
    isconnected_block = ""
    if mode == "isconnected-call":
        isconnected_block = """
    -- Step 4: Call ar1.IsConnected() explicitly
    progress("before_IsConnected")
    local ic_ok, ic_ret = pcall(function() return ar1.IsConnected() end)
    if not ic_ok then
        status = "RADARLINK_ENTRYPOINT_MISSING"
        progress("after_IsConnected", "ERROR: " .. tostring(ic_ret))
        error("RADARLINK_ENTRYPOINT_MISSING: " .. tostring(ic_ret))
    end
    progress("after_IsConnected", tostring(ic_ret))
    ic_ret_str = esc(ic_ret)
"""
    else:
        isconnected_block = """
    local ic_ret_str = "null"
"""

    return f"""\
-- lua-launch ar1-readonly-probe
-- run_id: {run_id}
-- mode: {mode}

local run_id = "{run_id}"
local out_path = [[{result_path}]]
local jsonl_path = [[{jsonl_path}]]

local function esc(s)
    if s == nil then return "null" end
    s = tostring(s)
    s = s:gsub("\\\\", "\\\\\\\\")
    s = s:gsub('"', '\\\\"')
    s = s:gsub("\\r", "\\\\r")
    s = s:gsub("\\n", "\\\\n")
    s = s:gsub("\\t", "\\\\t")
    return '"' .. s .. '"'
end
local function line(f, s) f:write(s); f:write("\\n") end

local function progress(step, detail)
    local lf = io.open(jsonl_path, "a")
    if lf then
        if detail then
            line(lf, '{{"step": ' .. esc(step) .. ', "detail": ' .. esc(detail) .. '}}')
        else
            line(lf, '{{"step": ' .. esc(step) .. '}}')
        end
        lf:close()
    end
end

local status = "NO_LUA_START"

local ok, err = pcall(function()
    local lf = io.open(jsonl_path, "w"); if lf then lf:close() end
    progress("script_started")

    progress("before_startup_lite")
    local lite_ok, lite_err = pcall(function()
{snippet}
    end)
    progress("after_startup_lite", tostring(lite_ok) .. " " .. tostring(lite_err))

    if not lite_ok then
        status = "STARTUP_LITE_FAILED"
        error("STARTUP_LITE_FAILED: " .. tostring(lite_err))
    end

    progress("check_ar1_type", type(ar1))
    if type(ar1) ~= "table" then
        status = "AR1_MISSING"
        error("AR1_MISSING: type(ar1) = " .. type(ar1))
    end

    local ar1_connect_exists = (ar1.Connect ~= nil)
    local ar1_isconnected_exists = (ar1.IsConnected ~= nil)
    local ar1_sopcontrol_exists = (ar1.SOPControl ~= nil)
    progress("ar1_methods", "Connect=" .. tostring(ar1_connect_exists) .. " IsConnected=" .. tostring(ar1_isconnected_exists) .. " SOPControl=" .. tostring(ar1_sopcontrol_exists))
{isconnected_block}
    status = "AR1_READONLY_OK"

    local f = io.open(out_path, "w")
    if not f then error("Cannot open result file") end

    line(f, "{{")
    line(f, '  "run_id": ' .. esc(run_id) .. ',')
    line(f, '  "executed": true,')
    line(f, '  "status": ' .. esc(status) .. ',')
    line(f, '  "type_ar1": ' .. esc(type(ar1)) .. ',')
    line(f, '  "ar1_connect_exists": ' .. tostring(ar1_connect_exists) .. ',')
    line(f, '  "ar1_isconnected_exists": ' .. tostring(ar1_isconnected_exists) .. ',')
    line(f, '  "ar1_sopcontrol_exists": ' .. tostring(ar1_sopcontrol_exists) .. ',')
    line(f, '  "is_connected_return": ' .. ic_ret_str .. ',')
    line(f, '  "error": null')
    line(f, "}}")
    f:close()
end)

if not ok then
    local f = io.open(out_path, "w")
    if f then
        line(f, "{{")
        line(f, '  "run_id": ' .. esc(run_id) .. ',')
        line(f, '  "executed": false,')
        line(f, '  "status": ' .. esc(status) .. ',')
        line(f, '  "error": ' .. esc(tostring(err)))
        line(f, "}}")
        f:close()
    end
end
"""


def build_lua_launch_connect_only(
    run_id: str,
    result_path: str,
    jsonl_path: str,
    com_num: int,
    baud: int = 115200,
    timeout_ms: int = 1000,
) -> str:
    result_path = result_path.replace("\\", "/")
    jsonl_path = jsonl_path.replace("\\", "/")
    snippet = _STARTUP_LITE_SNIPPET.replace("\\", "\\\\")
    return f"""\
-- lua-launch connect-only
-- run_id: {run_id}
-- Safety: NO SOPControl, NO firmware, NO PowerOn, NO RfEnable, NO DCA

local run_id = "{run_id}"
local out_path = [[{result_path}]]
local jsonl_path = [[{jsonl_path}]]

local function esc(s)
    if s == nil then return "null" end
    s = tostring(s)
    s = s:gsub("\\\\", "\\\\\\\\")
    s = s:gsub('"', '\\\\"')
    s = s:gsub("\\r", "\\\\r")
    s = s:gsub("\\n", "\\\\n")
    s = s:gsub("\\t", "\\\\t")
    return '"' .. s .. '"'
end
local function line(f, s) f:write(s); f:write("\\n") end

local function progress(step, detail)
    local lf = io.open(jsonl_path, "a")
    if lf then
        if detail then
            line(lf, '{{"step": ' .. esc(step) .. ', "detail": ' .. esc(detail) .. '}}')
        else
            line(lf, '{{"step": ' .. esc(step) .. '}}')
        end
        lf:close()
    end
end

local status = "NO_LUA_START"

local ok, err = pcall(function()
    local lf = io.open(jsonl_path, "w"); if lf then lf:close() end
    progress("script_started")

    progress("before_startup_lite")
    local lite_ok, lite_err = pcall(function()
{snippet}
    end)
    progress("after_startup_lite", tostring(lite_ok) .. " " .. tostring(lite_err))

    if not lite_ok then
        status = "STARTUP_LITE_FAILED"
        error("STARTUP_LITE_FAILED: " .. tostring(lite_err))
    end

    progress("check_ar1_type", type(ar1))
    if type(ar1) ~= "table" then
        status = "AR1_MISSING"
        error("AR1_MISSING: type(ar1) = " .. type(ar1))
    end

    progress("before_Connect", "COM{com_num} baud={baud} timeout={timeout_ms}")
    local c_ok, c_ret = pcall(function() return ar1.Connect({com_num}, {baud}, {timeout_ms}) end)
    if not c_ok then
        status = "CONNECT_EXCEPTION_NULLREF"
        progress("after_Connect", "ERROR: " .. tostring(c_ret))
        error("HUNG_AT_CONNECT: " .. tostring(c_ret))
    end
    progress("after_Connect", tostring(c_ret))

    if c_ret == 0 then
        status = "CONNECT_SUCCESS"
    else
        status = "CONNECT_RETURNED_ERROR"
    end

    local f = io.open(out_path, "w")
    if not f then error("Cannot open result file") end

    line(f, "{{")
    line(f, '  "run_id": ' .. esc(run_id) .. ',')
    line(f, '  "executed": true,')
    line(f, '  "status": ' .. esc(status) .. ',')
    line(f, '  "com_number": {com_num},')
    line(f, '  "baud": {baud},')
    line(f, '  "timeout_ms": {timeout_ms},')
    line(f, '  "connect_return": ' .. esc(c_ret) .. ',')
    line(f, '  "error": null')
    line(f, "}}")
    f:close()
end)

if not ok then
    local f = io.open(out_path, "w")
    if f then
        line(f, "{{")
        line(f, '  "run_id": ' .. esc(run_id) .. ',')
        line(f, '  "executed": false,')
        line(f, '  "status": ' .. esc(status) .. ',')
        line(f, '  "error": ' .. esc(tostring(err)))
        line(f, "}}")
        f:close()
    end
end
"""


def build_lua_manual_connect_script(run_id: str, result_path: str, com_num: int, baud: int) -> str:
    result_path = result_path.replace("\\", "/")
    return f"""\
-- manual connect-script
-- run_id: {run_id}
local run_id = "{run_id}"
local out_path = [[{result_path}]]
local function esc(s)
    if s == nil then return "null" end
    s = tostring(s)
    s = s:gsub("\\\\", "\\\\\\\\")
    s = s:gsub('"', '\\\\"')
    s = s:gsub("\\r", "\\\\r")
    s = s:gsub("\\n", "\\\\n")
    s = s:gsub("\\t", "\\\\t")
    return '"' .. s .. '"'
end
local function line(f, s) f:write(s); f:write("\\n") end

local status = "NO_START"
local c_ret_str = "null"

local ok, err = pcall(function()
    status = "CHECKING_AR1"
    if type(ar1) ~= "table" then
        status = "AR1_MISSING"
        error("AR1_MISSING")
    end
    if ar1.Connect == nil then
        status = "CONNECT_METHOD_MISSING"
        error("CONNECT_METHOD_MISSING")
    end
    
    status = "BEFORE_CONNECT"
    WriteToLog("Attempting ar1.Connect({com_num}, {baud}, 1000)...\\n", "blue")
    
    local c_ok, c_ret = pcall(function() return ar1.Connect({com_num}, {baud}, 1000) end)
    
    if not c_ok then
        status = "CONNECT_EXCEPTION_NULLREF"
        error("CONNECT_EXCEPTION: " .. tostring(c_ret))
    end
    c_ret_str = esc(c_ret)
    if c_ret == 0 then
        status = "CONNECT_SUCCESS"
    else
        status = "CONNECT_RETURNED_ERROR"
    end
    
    local f = io.open(out_path, "w")
    if f then
        line(f, "{{")
        line(f, '  "run_id": ' .. esc(run_id) .. ',')
        line(f, '  "executed": true,')
        line(f, '  "status": ' .. esc(status) .. ',')
        line(f, '  "connect_return": ' .. c_ret_str .. ',')
        line(f, '  "error": null')
        line(f, "}}")
        f:close()
    end
end)

if not ok then
    local f = io.open(out_path, "w")
    if f then
        line(f, "{{")
        line(f, '  "run_id": ' .. esc(run_id) .. ',')
        line(f, '  "executed": false,')
        line(f, '  "status": ' .. esc(status) .. ',')
        line(f, '  "error": ' .. esc(tostring(err)))
        line(f, "}}")
        f:close()
    end
end
"""


def build_lua_launch_ar1_methods(run_id: str, result_path: str, filter_str: str) -> str:
    result_path = result_path.replace("\\", "/")
    snippet = _STARTUP_LITE_SNIPPET.replace("\\", "\\\\")
    return f"""\
local run_id = "{run_id}"
local out_path = [[{result_path}]]
local filter_str = "{filter_str}"

local function esc(s)
    if s == nil then return "null" end
    s = tostring(s)
    s = s:gsub("\\\\", "\\\\\\\\")
    s = s:gsub('"', '\\\\"')
    s = s:gsub("\\r", "\\\\r")
    s = s:gsub("\\n", "\\\\n")
    s = s:gsub("\\t", "\\\\t")
    return '"' .. s .. '"'
end
local function line(f, s) f:write(s); f:write("\\n") end

local ok, err = pcall(function()
{snippet}
    
    local methods = {{}}
    if type(ar1) == "table" then
        for k, v in pairs(ar1) do
            if type(v) == "function" or type(v) == "userdata" then
                if filter_str == "" or string.find(string.lower(k), string.lower(filter_str)) then
                    table.insert(methods, k)
                end
            end
        end
    end
    
    table.sort(methods)
    
    local f = io.open(out_path, "w")
    if f then
        line(f, "{{")
        line(f, '  "run_id": ' .. esc(run_id) .. ',')
        line(f, '  "executed": true,')
        line(f, '  "methods": [')
        for i, m in ipairs(methods) do
            if i < #methods then
                line(f, '    ' .. esc(m) .. ',')
            else
                line(f, '    ' .. esc(m))
            end
        end
        line(f, '  ]')
        line(f, "}}")
        f:close()
    end
end)

if not ok then
    local f = io.open(out_path, "w")
    if f then
        line(f, "{{")
        line(f, '  "run_id": ' .. esc(run_id) .. ',')
        line(f, '  "executed": false,')
        line(f, '  "error": ' .. esc(tostring(err)))
        line(f, "}}")
        f:close()
    end
end
"""


def build_lua_launch_radarapi_init_probe(run_id: str, result_path: str, jsonl_path: str, mode: str) -> str:
    result_path = result_path.replace("\\", "/")
    jsonl_path = jsonl_path.replace("\\", "/")
    snippet = _STARTUP_LITE_SNIPPET.replace("\\", "\\\\")
    
    return f"""\
local run_id = "{run_id}"
local out_path = [[{result_path}]]
local jsonl_path = [[{jsonl_path}]]
local mode = "{mode}"

local function esc(s)
    if s == nil then return "null" end
    s = tostring(s)
    s = s:gsub("\\\\", "\\\\\\\\")
    s = s:gsub('"', '\\\\"')
    s = s:gsub("\\r", "\\\\r")
    s = s:gsub("\\n", "\\\\n")
    s = s:gsub("\\t", "\\\\t")
    return '"' .. s .. '"'
end
local function line(f, s) f:write(s); f:write("\\n") end
local function progress(step, detail)
    local lf = io.open(jsonl_path, "a")
    if lf then
        if detail then
            line(lf, '{{"step": ' .. esc(step) .. ', "detail": ' .. esc(detail) .. '}}')
        else
            line(lf, '{{"step": ' .. esc(step) .. '}}')
        end
        lf:close()
    end
end

local status = "NO_START"
local err_msg = "null"

local ok, err = pcall(function()
    local lf = io.open(jsonl_path, "w"); if lf then lf:close() end
    progress("script_started")

    progress("before_startup_lite")
    local lite_ok, lite_err = pcall(function()
{snippet}
    end)
    progress("after_startup_lite", tostring(lite_ok) .. " " .. tostring(lite_err))
    if not lite_ok then status = "STARTUP_LITE_FAILED"; error("STARTUP_LITE_FAILED") end

    if mode ~= "no-showgui" and mode ~= "rttt-no-showgui" then
        progress("before_ShowGui")
        local sg_ok, sg_err = pcall(function() ar1.ShowGui() end)
        progress("after_ShowGui", tostring(sg_ok) .. " " .. tostring(sg_err))
        if not sg_ok then status = "SHOWGUI_FAILED"; error("SHOWGUI_FAILED") end
    end

    if mode == "showgui-plus-getversion" or mode == "showgui-plus-loadsettings" or mode == "full" then
        progress("before_GetVersion")
        local gv_ok, gv_ret = pcall(function() return ar1.GetVersion() end)
        progress("after_GetVersion", tostring(gv_ok) .. " " .. tostring(gv_ret))
        
        progress("before_SelectRadarMode")
        local srm_ok, srm_ret = pcall(function() return ar1.SelectRadarMode(0) end)
        progress("after_SelectRadarMode", tostring(srm_ok) .. " " .. tostring(srm_ret))
        
        progress("before_selectCascadeMode")
        local scm_ok, scm_ret = pcall(function() return ar1.selectCascadeMode(0) end)
        progress("after_selectCascadeMode", tostring(scm_ok) .. " " .. tostring(scm_ret))
    end
    
    if mode == "showgui-plus-loadsettings" or mode == "full" then
        progress("before_LoadSettings")
    local ls_ok, ls_ret = pcall(function() return ar1.LoadSettings([[C:/Users/khams008/AppData/Roaming/RSTD/ar1gui.ini]]) end)
        progress("after_LoadSettings", tostring(ls_ok) .. " " .. tostring(ls_ret))
    end

    if mode == "full" then
        progress("before_NetStart")
        local ns_ok, ns_ret = pcall(function() return RSTD.NetStart() end)
        progress("after_NetStart", tostring(ns_ok) .. " " .. tostring(ns_ret))
    end

    status = "INIT_PROBE_SUCCESS"
    local f = io.open(out_path, "w")
    if f then
        line(f, "{{")
        line(f, '  "run_id": ' .. esc(run_id) .. ',')
        line(f, '  "executed": true,')
        line(f, '  "status": ' .. esc(status) .. ',')
        line(f, '  "error": null')
        line(f, "}}")
        f:close()
    end
end)

if not ok then
    local f = io.open(out_path, "w")
    if f then
        line(f, "{{")
        line(f, '  "run_id": ' .. esc(run_id) .. ',')
        line(f, '  "executed": false,')
        line(f, '  "status": ' .. esc(status) .. ',')
        line(f, '  "error": ' .. esc(tostring(err)))
        line(f, "}}")
        f:close()
    end
end
"""

def build_lua_launch_radarapi_connect_probe(run_id: str, result_path: str, jsonl_path: str, mode: str, com_num: int, baud: int) -> str:
    result_path = result_path.replace("\\", "/")
    jsonl_path = jsonl_path.replace("\\", "/")
    snippet = _STARTUP_LITE_SNIPPET.replace("\\", "\\\\")
    
    return f"""\
local run_id = "{run_id}"
local out_path = [[{result_path}]]
local jsonl_path = [[{jsonl_path}]]
local mode = "{mode}"

local function esc(s)
    if s == nil then return "null" end
    s = tostring(s)
    s = s:gsub("\\\\", "\\\\\\\\")
    s = s:gsub('"', '\\\\"')
    s = s:gsub("\\r", "\\\\r")
    s = s:gsub("\\n", "\\\\n")
    s = s:gsub("\\t", "\\\\t")
    return '"' .. s .. '"'
end
local function line(f, s) f:write(s); f:write("\\n") end
local function progress(step, detail)
    local lf = io.open(jsonl_path, "a")
    if lf then
        if detail then
            line(lf, '{{"step": ' .. esc(step) .. ', "detail": ' .. esc(detail) .. '}}')
        else
            line(lf, '{{"step": ' .. esc(step) .. '}}')
        end
        lf:close()
    end
end

local status = "NO_START"
local err_msg = "null"
local c_ret_str = "null"

local ok, err = pcall(function()
    local lf = io.open(jsonl_path, "w"); if lf then lf:close() end
    progress("script_started")

    progress("before_startup_lite")
    local lite_ok, lite_err = pcall(function()
{snippet}
    end)
    progress("after_startup_lite", tostring(lite_ok) .. " " .. tostring(lite_err))
    if not lite_ok then status = "STARTUP_LITE_FAILED"; error("STARTUP_LITE_FAILED") end

    if mode ~= "no-showgui" and mode ~= "rttt-no-showgui" then
        progress("before_ShowGui")
        local sg_ok, sg_err = pcall(function() ar1.ShowGui() end)
        progress("after_ShowGui", tostring(sg_ok) .. " " .. tostring(sg_err))
        if not sg_ok then status = "SHOWGUI_FAILED"; error("SHOWGUI_FAILED") end
    end

    if mode == "showgui-plus-getversion" or mode == "showgui-plus-loadsettings" or mode == "full" then
        progress("before_GetVersion")
        local gv_ok = pcall(function() return ar1.GetVersion() end)
        progress("after_GetVersion", tostring(gv_ok))
        
        progress("before_SelectRadarMode")
        local srm_ok = pcall(function() return ar1.SelectRadarMode(0) end)
        progress("after_SelectRadarMode", tostring(srm_ok))
        
        progress("before_selectCascadeMode")
        local scm_ok = pcall(function() return ar1.selectCascadeMode(0) end)
        progress("after_selectCascadeMode", tostring(scm_ok))
    end
    
    if mode == "showgui-plus-loadsettings" or mode == "full" then
        progress("before_LoadSettings")
    local ls_ok, ls_ret = pcall(function() return ar1.LoadSettings([[C:/Users/khams008/AppData/Roaming/RSTD/ar1gui.ini]]) end)
        progress("after_LoadSettings", tostring(ls_ok))
    end

    if mode == "full" then
        progress("before_NetStart")
        local ns_ok = pcall(function() return RSTD.NetStart() end)
        progress("after_NetStart", tostring(ns_ok))
    end

    progress("before_Connect", "COM{com_num} baud={baud} timeout=1000")
    local c_ok, c_ret = pcall(function() return ar1.Connect({com_num}, {baud}, 1000) end)
    
    if not c_ok then
        status = "CONNECT_EXCEPTION_NULLREF"
        progress("after_Connect", "ERROR: " .. tostring(c_ret))
        error("CONNECT_EXCEPTION: " .. tostring(c_ret))
    end
    
    progress("after_Connect", tostring(c_ret))
    c_ret_str = esc(c_ret)
    
    if c_ret == 0 then
        status = "CONNECT_SUCCESS"
    else
        status = "CONNECT_RETURNED_ERROR"
    end

    local f = io.open(out_path, "w")
    if f then
        line(f, "{{")
        line(f, '  "run_id": ' .. esc(run_id) .. ',')
        line(f, '  "executed": true,')
        line(f, '  "status": ' .. esc(status) .. ',')
        line(f, '  "connect_return": ' .. c_ret_str .. ',')
        line(f, '  "error": null')
        line(f, "}}")
        f:close()
    end
end)

if not ok then
    local f = io.open(out_path, "w")
    if f then
        line(f, "{{")
        line(f, '  "run_id": ' .. esc(run_id) .. ',')
        line(f, '  "executed": false,')
        line(f, '  "status": ' .. esc(status) .. ',')
        line(f, '  "error": ' .. esc(tostring(err)))
        line(f, "}}")
        f:close()
    end
end
"""

# ---------------------------------------------------------------------------
# connection stage official builders
# ---------------------------------------------------------------------------

def build_lua_launch_connection_connect_gui(
    run_id: str, result_path: str, jsonl_path: str,
    com_num: int, baud: int,
) -> str:
    """Official connection backend using startup-lite-v3 + ShowGui + Connect."""
    result_path = result_path.replace("\\", "/")
    jsonl_path = jsonl_path.replace("\\", "/")
    snippet_v3 = _v3_snippet_escaped()
    
    return f"""\
local run_id = "{run_id}"
local out_path = [[{result_path}]]
local jsonl_path = [[{jsonl_path}]]

local function esc(s)
    if s == nil then return "null" end
    s = tostring(s)
    s = s:gsub("\\\\", "\\\\\\\\")
    s = s:gsub('"', '\\\\"')
    s = s:gsub("\\r", "\\\\r")
    s = s:gsub("\\n", "\\\\n")
    s = s:gsub("\\t", "\\\\t")
    return '"' .. s .. '"'
end
local function line(f, s) f:write(s); f:write("\\n") end
local function progress(step, detail)
    local lf = io.open(jsonl_path, "a")
    if lf then
        if detail then
            line(lf, '{{"step": ' .. esc(step) .. ', "detail": ' .. esc(detail) .. '}}')
        else
            line(lf, '{{"step": ' .. esc(step) .. '}}')
        end
        lf:close()
    end
end

local status = "NO_START"
local c_ret_str = "null"
local dv_ret_str = "null"
local fb_ret_str = "null"
local cv_ret_str = "null"

local gui_ver = "unknown"
local rl_ver = "unknown"
local pp_ver = "unknown"

local function safe_call(fn)
    local ok, ret = pcall(fn)
    if ok then return ret else return nil end
end

local ok, err = pcall(function()
    local lf = io.open(jsonl_path, "w"); if lf then lf:close() end
    progress("script_started")

    progress("before_startup_lite_v3")
    local lite_ok, lite_err = pcall(function()
{snippet_v3}
    end)
    progress("after_startup_lite_v3", tostring(lite_ok) .. " " .. tostring(lite_err))
    if not lite_ok then status = "STARTUP_LITE_V3_FAILED"; error("STARTUP_LITE_V3_FAILED") end

    progress("check_ar1_type", type(ar1))
    if type(ar1) ~= "table" then
        status = "AR1_MISSING"
        error("AR1_MISSING")
    end

    progress("before_ShowGui")
    local sg_ok, sg_err = pcall(function() ar1.ShowGui() end)
    progress("after_ShowGui", tostring(sg_ok) .. " " .. tostring(sg_err))
    if not sg_ok then status = "SHOWGUI_FAILED"; error("SHOWGUI_FAILED") end

    progress("before_Connect", "COM{com_num} baud={baud} timeout=1000")
    local c_ok, c_ret = pcall(function() return ar1.Connect({com_num}, {baud}, 1000) end)

    if not c_ok then
        status = "CONNECT_EXCEPTION"
        progress("after_Connect", "ERROR: " .. tostring(c_ret))
        error("CONNECT_EXCEPTION: " .. tostring(c_ret))
    end
    progress("after_Connect", tostring(c_ret))
    c_ret_str = esc(c_ret)

    if c_ret == 0 then
        -- Perform selections
        progress("before_deviceVariantSelection", "XWR2944")
        local dv_ok, dv_ret = pcall(function() return ar1.deviceVariantSelection("XWR2944") end)
        progress("after_deviceVariantSelection", tostring(dv_ret))
        dv_ret_str = esc(dv_ret)
        
        progress("before_frequencyBandSelection", "77G")
        local fb_ok, fb_ret = pcall(function() return ar1.frequencyBandSelection("77G") end)
        progress("after_frequencyBandSelection", tostring(fb_ret))
        fb_ret_str = esc(fb_ret)
        
        progress("before_SelectChipVersion", "AWR2944")
        local cv_ok, cv_ret = pcall(function() return ar1.SelectChipVersion("AWR2944") end)
        progress("after_SelectChipVersion", tostring(cv_ret))
        cv_ret_str = esc(cv_ret)

        if dv_ret == 0 and fb_ret == 0 and cv_ret == 0 then
            status = "CONNECTION_GUI_SUCCESS"
        else
            status = "CONNECTION_GUI_SELECTION_FAILED"
        end

        -- Try to retrieve versions
        local gv = safe_call(function() return ar1.GuiVersion() end)
        if gv then gui_ver = tostring(gv) end
        
        if type(ar1.GetRadarLinkVersion) == "function" then
            local rlv = safe_call(function() return ar1.GetRadarLinkVersion() end)
            if rlv then rl_ver = tostring(rlv) end
        end
        if type(ar1.GetPostProcVersion) == "function" then
            local ppv = safe_call(function() return ar1.GetPostProcVersion() end)
            if ppv then pp_ver = tostring(ppv) end
        end

    else
        status = "CONNECT_RETURNED_ERROR"
    end

    local f = io.open(out_path, "w")
    if f then
        line(f, "{{")
        line(f, '  "run_id": ' .. esc(run_id) .. ',')
        line(f, '  "executed": true,')
        line(f, '  "status": ' .. esc(status) .. ',')
        line(f, '  "connect_return": ' .. c_ret_str .. ',')
        line(f, '  "device_variant_selection_return": ' .. dv_ret_str .. ',')
        line(f, '  "frequency_band_selection_return": ' .. fb_ret_str .. ',')
        line(f, '  "chip_version_selection_return": ' .. cv_ret_str .. ',')
        line(f, '  "full_reset_return": ' .. fr_ret_str .. ',')
        line(f, '  "gui_version": ' .. esc(gui_ver) .. ',')
        line(f, '  "radar_link_version": ' .. esc(rl_ver) .. ',')
        line(f, '  "post_proc_version": ' .. esc(pp_ver) .. ',')
        line(f, '  "error": null')
        line(f, "}}")
        f:close()
    end
end)

if not ok then
    local f = io.open(out_path, "w")
    if f then
        line(f, "{{")
        line(f, '  "run_id": ' .. esc(run_id) .. ',')
        line(f, '  "executed": false,')
        line(f, '  "status": ' .. esc(status) .. ',')
        line(f, '  "error": ' .. esc(tostring(err)))
        line(f, "}}")
        f:close()
    end
end
"""

def build_lua_launch_connection_sop_set_only(
    run_id: str, result_path: str, jsonl_path: str,
    mode: int,
) -> str:
    """Run SOPControl on an already initialized/connected GUI."""
    result_path = result_path.replace("\\", "/")
    jsonl_path = jsonl_path.replace("\\", "/")
    return f"""\
local run_id = "{run_id}"
local out_path = [[{result_path}]]
local jsonl_path = [[{jsonl_path}]]

local function esc(s)
    if s == nil then return "null" end
    s = tostring(s)
    s = s:gsub("\\\\", "\\\\\\\\")
    s = s:gsub('"', '\\\\"')
    s = s:gsub("\\r", "\\\\r")
    s = s:gsub("\\n", "\\\\n")
    s = s:gsub("\\t", "\\\\t")
    return '"' .. s .. '"'
end
local function line(f, s) f:write(s); f:write("\\n") end
local function progress(step, detail)
    local lf = io.open(jsonl_path, "a")
    if lf then
        if detail then
            line(lf, '{{"step": ' .. esc(step) .. ', "detail": ' .. esc(detail) .. '}}')
        else
            line(lf, '{{"step": ' .. esc(step) .. '}}')
        end
        lf:close()
    end
end

local status = "NO_START"
local sop_ret_str = "null"

local ok, err = pcall(function()
    local lf = io.open(jsonl_path, "w"); if lf then lf:close() end
    progress("script_started")

    progress("check_ar1_type", type(ar1))
    if type(ar1) ~= "table" then
        status = "AR1_MISSING"
        error("AR1_MISSING: this script must be run in an already-initialized mmWave Studio context")
    end

    progress("before_SOPControl", "{mode}")
    local s_ok, s_ret = pcall(function() return ar1.SOPControl({mode}) end)

    if not s_ok then
        status = "SOPCONTROL_EXCEPTION"
        progress("after_SOPControl", "ERROR: " .. tostring(s_ret))
        error("SOPCONTROL_EXCEPTION: " .. tostring(s_ret))
    end
    progress("after_SOPControl", tostring(s_ret))
    sop_ret_str = esc(s_ret)

    if s_ret == 0 then
        status = "SOPCONTROL_SUCCESS"
    else
        status = "SOPCONTROL_RETURNED_ERROR"
    end

    local f = io.open(out_path, "w")
    if f then
        line(f, "{{")
        line(f, '  "run_id": ' .. esc(run_id) .. ',')
        line(f, '  "executed": true,')
        line(f, '  "status": ' .. esc(status) .. ',')
        line(f, '  "sopcontrol_return": ' .. sop_ret_str .. ',')
        line(f, '  "error": null')
        line(f, "}}")
        f:close()
    end
end)

if not ok then
    local f = io.open(out_path, "w")
    if f then
        line(f, "{{")
        line(f, '  "run_id": ' .. esc(run_id) .. ',')
        line(f, '  "executed": false,')
        line(f, '  "status": ' .. esc(status) .. ',')
        line(f, '  "error": ' .. esc(tostring(err)))
        line(f, "}}")
        f:close()
    end
end
"""


# ---------------------------------------------------------------------------
# Connection sequences with retry logic
# ---------------------------------------------------------------------------

# Valid sequences for connect-gui and return3-diag
CONNECT_SEQUENCES = [
    "showgui-connect",
    "showgui-sleep-connect",
    "showgui-sop-sleep-connect",
    "gui-set1-fullreset-connect",
    "gui-set1-fullreset-aw2944-connect",
    "select-set-connect",
    "showgui-select-sop-connect",
    "showgui-sop-reset-longwait-connect",
]


def build_lua_launch_connection_sequenced(
    run_id: str, result_path: str, jsonl_path: str,
    com_num: int, baud: int, sequence: str,
    retry_on_3: bool = True,
) -> str:
    """Generate a connection script with a specific sequence and optional retry.

    Sequences:
      A. showgui-connect
      B. showgui-sleep-connect
      C. showgui-sop-sleep-connect
      D. showgui-select-sop-connect
      E. showgui-sop-reset-longwait-connect
      F. select-set-connect
      G. gui-set1-fullreset-connect (DEFAULT)
      H. gui-set1-fullreset-aw2944-connect

    If retry_on_3 is True and the first Connect returns 3,
    the script waits 3s and retries once.
    """
    result_path = result_path.replace("\\", "/")
    jsonl_path = jsonl_path.replace("\\", "/")
    snippet_v3 = _v3_snippet_escaped()

    # Build the sequence-specific Lua block
    seq_blocks = {


        "gui-set1-fullreset-connect": """
    progress("before_selectRadarMode", "0")
    local sr_ok, sr_ret = pcall(function() return ar1.selectRadarMode(0) end)
    progress("after_selectRadarMode", tostring(sr_ret))

    progress("before_selectCascadeMode", "0")
    local sc_ok, sc_ret = pcall(function() return ar1.selectCascadeMode(0) end)
    progress("after_selectCascadeMode", tostring(sc_ret))

    progress("before_LoadSettings")
    local ls_ok, ls_ret = pcall(function() return ar1.LoadSettings([[C:/Users/khams008/AppData/Roaming/RSTD/ar1gui.ini]]) end)
    progress("after_LoadSettings", tostring(ls_ret))

    progress("before_frequencyBandSelection", "77G")
    local fb_ok, fb_ret = pcall(function() return ar1.frequencyBandSelection("77G") end)
    progress("after_frequencyBandSelection", tostring(fb_ret))
    fb_ret_str = esc(fb_ret)

    progress("before_SelectChipVersion", "AR1642")
    local cv_ok, cv_ret = pcall(function() return ar1.SelectChipVersion("AR1642") end)
    progress("after_SelectChipVersion", tostring(cv_ret))
    cv_ret_str = esc(cv_ret)

    progress("before_deviceVariantSelection", "XWR2944")
    local dv_ok, dv_ret = pcall(function() return ar1.deviceVariantSelection("XWR2944") end)
    progress("after_deviceVariantSelection", tostring(dv_ret))
    dv_ret_str = esc(dv_ret)

    progress("before_FullReset")
    local fr_ok, fr_ret = pcall(function() return ar1.FullReset() end)
    progress("after_FullReset", tostring(fr_ret))
    fr_ret_str = esc(fr_ret)

    progress("before_Sleep", "1000 ms")
    RSTD.Sleep(1000)
    progress("after_Sleep")

    progress("before_SOPControl", "mode=2")
    local sop_ok, sop_ret = pcall(function() return ar1.SOPControl(2) end)
    if not sop_ok then
        progress("after_SOPControl", "ERROR: " .. tostring(sop_ret))
        sop_ret_str = esc(tostring(sop_ret))
    else
        progress("after_SOPControl", tostring(sop_ret))
        sop_ret_str = esc(sop_ret)
    end

    progress("before_Sleep", "3000 ms")
    RSTD.Sleep(3000)
    progress("after_Sleep")
""",
        "gui-set1-fullreset-aw2944-connect": """
    progress("before_selectRadarMode", "0")
    local sr_ok, sr_ret = pcall(function() return ar1.selectRadarMode(0) end)
    progress("after_selectRadarMode", tostring(sr_ret))

    progress("before_selectCascadeMode", "0")
    local sc_ok, sc_ret = pcall(function() return ar1.selectCascadeMode(0) end)
    progress("after_selectCascadeMode", tostring(sc_ret))

    progress("before_LoadSettings")
    local ls_ok, ls_ret = pcall(function() return ar1.LoadSettings([[C:/Users/khams008/AppData/Roaming/RSTD/ar1gui.ini]]) end)
    progress("after_LoadSettings", tostring(ls_ret))

    progress("before_frequencyBandSelection", "77G")
    local fb_ok, fb_ret = pcall(function() return ar1.frequencyBandSelection("77G") end)
    progress("after_frequencyBandSelection", tostring(fb_ret))
    fb_ret_str = esc(fb_ret)

    progress("before_SelectChipVersion", "AWR2944")
    local cv_ok, cv_ret = pcall(function() return ar1.SelectChipVersion("AWR2944") end)
    progress("after_SelectChipVersion", tostring(cv_ret))
    cv_ret_str = esc(cv_ret)

    progress("before_deviceVariantSelection", "XWR2944")
    local dv_ok, dv_ret = pcall(function() return ar1.deviceVariantSelection("XWR2944") end)
    progress("after_deviceVariantSelection", tostring(dv_ret))
    dv_ret_str = esc(dv_ret)

    progress("before_FullReset")
    local fr_ok, fr_ret = pcall(function() return ar1.FullReset() end)
    progress("after_FullReset", tostring(fr_ret))
    fr_ret_str = esc(fr_ret)

    progress("before_Sleep", "1000 ms")
    RSTD.Sleep(1000)
    progress("after_Sleep")

    progress("before_SOPControl", "mode=2")
    local sop_ok, sop_ret = pcall(function() return ar1.SOPControl(2) end)
    if not sop_ok then
        progress("after_SOPControl", "ERROR: " .. tostring(sop_ret))
        sop_ret_str = esc(tostring(sop_ret))
    else
        progress("after_SOPControl", tostring(sop_ret))
        sop_ret_str = esc(sop_ret)
    end

    progress("before_Sleep", "3000 ms")
    RSTD.Sleep(3000)
    progress("after_Sleep")
""",
        "select-set-connect": """
    progress("before_frequencyBandSelection", "77G")
    local fb_ok, fb_ret = pcall(function() return ar1.frequencyBandSelection("77G") end)
    progress("after_frequencyBandSelection", tostring(fb_ret))
    fb_ret_str = esc(fb_ret)

    progress("before_deviceVariantSelection", "XWR2944")
    local dv_ok, dv_ret = pcall(function() return ar1.deviceVariantSelection("XWR2944") end)
    progress("after_deviceVariantSelection", tostring(dv_ret))
    dv_ret_str = esc(dv_ret)

    progress("before_SelectChipVersion", "AWR2944")
    local cv_ok, cv_ret = pcall(function() return ar1.SelectChipVersion("AWR2944") end)
    progress("after_SelectChipVersion", tostring(cv_ret))
    cv_ret_str = esc(cv_ret)

    progress("before_SOPControl", "mode=2")
    local sop_ok, sop_ret = pcall(function() return ar1.SOPControl(2) end)
    if not sop_ok then
        progress("after_SOPControl", "ERROR: " .. tostring(sop_ret))
        sop_ret_str = esc(tostring(sop_ret))
    else
        progress("after_SOPControl", tostring(sop_ret))
        sop_ret_str = esc(sop_ret)
    end

    progress("before_Sleep", "3000 ms")
    RSTD.Sleep(3000)
    progress("after_Sleep")
""",
        "showgui-connect": "",
        "showgui-sleep-connect": """
    progress("before_Sleep", "3000 ms")
    RSTD.Sleep(3000)
    progress("after_Sleep")
""",
        "showgui-sop-sleep-connect": """
    progress("before_SOPControl", "mode=2")
    local sop_ok, sop_ret = pcall(function() return ar1.SOPControl(2) end)
    if not sop_ok then
        progress("after_SOPControl", "ERROR: " .. tostring(sop_ret))
        sop_ret_str = esc(tostring(sop_ret))
    else
        progress("after_SOPControl", tostring(sop_ret))
        sop_ret_str = esc(sop_ret)
    end

    progress("before_Sleep", "3000 ms")
    RSTD.Sleep(3000)
    progress("after_Sleep")
""",
        "showgui-select-sop-connect": """
    progress("before_deviceVariantSelection", "XWR2944")
    local dv_ok, dv_ret = pcall(function() return ar1.deviceVariantSelection("XWR2944") end)
    progress("after_deviceVariantSelection", tostring(dv_ret))
    dv_ret_str = esc(dv_ret)

    progress("before_frequencyBandSelection", "77G")
    local fb_ok, fb_ret = pcall(function() return ar1.frequencyBandSelection("77G") end)
    progress("after_frequencyBandSelection", tostring(fb_ret))
    fb_ret_str = esc(fb_ret)

    progress("before_SelectChipVersion", "AWR2944")
    local cv_ok, cv_ret = pcall(function() return ar1.SelectChipVersion("AWR2944") end)
    progress("after_SelectChipVersion", tostring(cv_ret))
    cv_ret_str = esc(cv_ret)

    progress("before_SOPControl", "mode=2")
    local sop_ok, sop_ret = pcall(function() return ar1.SOPControl(2) end)
    if not sop_ok then
        progress("after_SOPControl", "ERROR: " .. tostring(sop_ret))
        sop_ret_str = esc(tostring(sop_ret))
    else
        progress("after_SOPControl", tostring(sop_ret))
        sop_ret_str = esc(sop_ret)
    end

    progress("before_Sleep", "3000 ms")
    RSTD.Sleep(3000)
    progress("after_Sleep")
""",
        "showgui-sop-reset-longwait-connect": """
    progress("before_SOPControl", "mode=2")
    local sop_ok, sop_ret = pcall(function() return ar1.SOPControl(2) end)
    if not sop_ok then
        progress("after_SOPControl", "ERROR: " .. tostring(sop_ret))
        sop_ret_str = esc(tostring(sop_ret))
    else
        progress("after_SOPControl", tostring(sop_ret))
        sop_ret_str = esc(sop_ret)
    end

    progress("before_Sleep", "8000 ms")
    RSTD.Sleep(8000)
    progress("after_Sleep")
""",
    }

    mid_block = seq_blocks.get(sequence, "")

    # Build retry block
    retry_block = ""
    if retry_on_3:
        retry_block = """
    if c_ret == 3 then
        progress("connect_returned_3_retry", "waiting 3000ms then retrying once")
        c1_ret_str = esc(c_ret)
        RSTD.Sleep(3000)
        progress("before_Connect_retry")
        local c2_ok, c2_ret = pcall(function() return ar1.Connect(""" + str(com_num) + ", " + str(baud) + """, 1000) end)
        if not c2_ok then
            progress("after_Connect_retry", "ERROR: " .. tostring(c2_ret))
            c2_ret_str = esc(tostring(c2_ret))
            status = "CONNECT_RETRY_EXCEPTION"
        else
            progress("after_Connect_retry", tostring(c2_ret))
            c2_ret_str = esc(c2_ret)
            c_ret = c2_ret
        end
    end
"""

    return f"""\
local run_id = "{run_id}"
local out_path = [[{result_path}]]
local jsonl_path = [[{jsonl_path}]]
local sequence = "{sequence}"

local function esc(s)
    if s == nil then return "null" end
    s = tostring(s)
    s = s:gsub("\\\\", "\\\\\\\\")
    s = s:gsub('"', '\\\\"')
    s = s:gsub("\\r", "\\\\r")
    s = s:gsub("\\n", "\\\\n")
    s = s:gsub("\\t", "\\\\t")
    return '"' .. s .. '"'
end
local function line(f, s) f:write(s); f:write("\\n") end
local function progress(step, detail)
    local lf = io.open(jsonl_path, "a")
    if lf then
        if detail then
            line(lf, '{{"step": ' .. esc(step) .. ', "detail": ' .. esc(detail) .. '}}')
        else
            line(lf, '{{"step": ' .. esc(step) .. '}}')
        end
        lf:close()
    end
end

local status = "NO_START"
local c_ret_str = "null"
local c1_ret_str = "null"
local c2_ret_str = "null"
local sop_ret_str = "null"
local dv_ret_str = "null"
local fb_ret_str = "null"
local cv_ret_str = "null"
local gui_ver = "unknown"

local ok, err = pcall(function()
    local lf = io.open(jsonl_path, "w"); if lf then lf:close() end
    progress("script_started")
    progress("sequence", sequence)

    progress("before_startup_lite_v3")
    local lite_ok, lite_err = pcall(function()
{snippet_v3}
    end)
    progress("after_startup_lite_v3", tostring(lite_ok) .. " " .. tostring(lite_err))
    if not lite_ok then status = "STARTUP_LITE_V3_FAILED"; error("STARTUP_LITE_V3_FAILED") end

    progress("check_ar1_type", type(ar1))
    if type(ar1) ~= "table" then
        status = "AR1_MISSING"
        error("AR1_MISSING")
    end

    progress("before_ShowGui")
    local sg_ok, sg_err = pcall(function() ar1.ShowGui() end)
    progress("after_ShowGui", tostring(sg_ok) .. " " .. tostring(sg_err))
    if not sg_ok then status = "SHOWGUI_FAILED"; error("SHOWGUI_FAILED") end
{mid_block}
    progress("before_Connect", "COM{com_num} baud={baud} timeout=1000")
    local c_ok, c_ret = pcall(function() return ar1.Connect({com_num}, {baud}, 1000) end)

    if not c_ok then
        status = "CONNECT_EXCEPTION"
        progress("after_Connect", "ERROR: " .. tostring(c_ret))
        c_ret_str = esc(tostring(c_ret))
        error("CONNECT_EXCEPTION: " .. tostring(c_ret))
    end
    progress("after_Connect", tostring(c_ret))
    c_ret_str = esc(c_ret)
{retry_block}
    if c_ret == 0 then
        -- Mark success only if selection, reset and SOP steps (if executed) also passed
        if (fb_ret_str == "null" or fb_ret_str == '"0"') and
           (dv_ret_str == "null" or dv_ret_str == '"0"') and
           (cv_ret_str == "null" or cv_ret_str == '"0"') and
           (fr_ret_str == "null" or fr_ret_str == '"0"') and
           (sop_ret_str == "null" or sop_ret_str == '"0"') then
            status = "CONNECTION_GUI_SUCCESS"
        else
            status = "CONNECTION_GUI_SELECTION_FAILED"
        end

        -- Retrieve version info
        local gv = nil
        pcall(function() gv = ar1.GuiVersion() end)
        if gv then gui_ver = tostring(gv) end

        -- Post-connect selections (if not already done in sequence)
        if dv_ret_str == "null" then
            progress("before_deviceVariantSelection", "XWR2944")
            local dv_ok2, dv_ret2 = pcall(function() return ar1.deviceVariantSelection("XWR2944") end)
            progress("after_deviceVariantSelection", tostring(dv_ret2))
            dv_ret_str = esc(dv_ret2)
        end
        if fb_ret_str == "null" then
            progress("before_frequencyBandSelection", "77G")
            local fb_ok2, fb_ret2 = pcall(function() return ar1.frequencyBandSelection("77G") end)
            progress("after_frequencyBandSelection", tostring(fb_ret2))
            fb_ret_str = esc(fb_ret2)
        end
        if cv_ret_str == "null" then
            progress("before_SelectChipVersion", "AWR2944")
            local cv_ok2, cv_ret2 = pcall(function() return ar1.SelectChipVersion("AWR2944") end)
            progress("after_SelectChipVersion", tostring(cv_ret2))
            cv_ret_str = esc(cv_ret2)
        end
    elseif c_ret == 3 then
        status = "CONNECT_RETURNED_3"
    else
        status = "CONNECT_RETURNED_ERROR"
    end

    local f = io.open(out_path, "w")
    if f then
        line(f, "{{")
        line(f, '  "run_id": ' .. esc(run_id) .. ',')
        line(f, '  "executed": true,')
        line(f, '  "sequence": ' .. esc(sequence) .. ',')
        line(f, '  "status": ' .. esc(status) .. ',')
        line(f, '  "connect_return": ' .. c_ret_str .. ',')
        line(f, '  "connect_return_1": ' .. c1_ret_str .. ',')
        line(f, '  "connect_return_2": ' .. c2_ret_str .. ',')
        line(f, '  "sop_return": ' .. sop_ret_str .. ',')
        line(f, '  "device_variant_selection_return": ' .. dv_ret_str .. ',')
        line(f, '  "frequency_band_selection_return": ' .. fb_ret_str .. ',')
        line(f, '  "chip_version_selection_return": ' .. cv_ret_str .. ',')
        line(f, '  "full_reset_return": ' .. fr_ret_str .. ',')
        line(f, '  "gui_version": ' .. esc(gui_ver) .. ',')
        line(f, '  "error": null')
        line(f, "}}")
        f:close()
    end
end)

if not ok then
    local f = io.open(out_path, "w")
    if f then
        line(f, "{{")
        line(f, '  "run_id": ' .. esc(run_id) .. ',')
        line(f, '  "executed": false,')
        line(f, '  "sequence": ' .. esc(sequence) .. ',')
        line(f, '  "status": ' .. esc(status) .. ',')
        line(f, '  "connect_return": ' .. c_ret_str .. ',')
        line(f, '  "connect_return_1": ' .. c1_ret_str .. ',')
        line(f, '  "connect_return_2": ' .. c2_ret_str .. ',')
        line(f, '  "sop_return": ' .. sop_ret_str .. ',')
        line(f, '  "error": ' .. esc(tostring(err)))
        line(f, "}}")
        f:close()
    end
end
"""
def build_lua_launch_connection_set1_discovery(
    run_id: str, result_path: str, jsonl_path: str,
) -> str:
    """Dump all ar1 method names matching specific keywords to find Set(1)."""
    result_path = result_path.replace("\\", "/")
    jsonl_path = jsonl_path.replace("\\", "/")
    snippet_v3 = _v3_snippet_escaped()

    return f"""\
local run_id = "{run_id}"
local out_path = [[{result_path}]]
local jsonl_path = [[{jsonl_path}]]

local function esc(s)
    if s == nil then return "null" end
    s = tostring(s)
    s = s:gsub("\\\\", "\\\\\\\\")
    s = s:gsub('"', '\\\\"')
    s = s:gsub("\\r", "\\\\r")
    s = s:gsub("\\n", "\\\\n")
    s = s:gsub("\\t", "\\\\t")
    return '"' .. s .. '"'
end
local function line(f, s) f:write(s); f:write("\\n") end
local function progress(step, detail)
    local lf = io.open(jsonl_path, "a")
    if lf then
        if detail then
            line(lf, '{{"step": ' .. esc(step) .. ', "detail": ' .. esc(detail) .. '}}')
        else
            line(lf, '{{"step": ' .. esc(step) .. '}}')
        end
        lf:close()
    end
end

local status = "NO_START"
local methods = {{}}

local ok, err = pcall(function()
    local lf = io.open(jsonl_path, "w"); if lf then lf:close() end
    progress("script_started")

    progress("before_startup_lite_v3")
    local lite_ok, lite_err = pcall(function()
{snippet_v3}
    end)
    progress("after_startup_lite_v3", tostring(lite_ok) .. " " .. tostring(lite_err))
    if not lite_ok then status = "STARTUP_LITE_V3_FAILED"; error("STARTUP_LITE_V3_FAILED") end

    progress("check_ar1_type", type(ar1))
    if type(ar1) ~= "table" then
        status = "AR1_MISSING"
        error("AR1_MISSING")
    end

    progress("before_ShowGui")
    local sg_ok, sg_err = pcall(function() ar1.ShowGui() end)
    progress("after_ShowGui", tostring(sg_ok) .. " " .. tostring(sg_err))
    if not sg_ok then status = "SHOWGUI_FAILED"; error("SHOWGUI_FAILED") end

    progress("dumping_ar1_methods")
    
    local keywords = {{"set", "reset", "sop", "variant", "device", "frequency", "band", "chip", "connect", "rs232", "ftdi", "target", "port", "com", "power"}}
    
    for k, v in pairs(ar1) do
        if type(v) == "function" or type(v) == "table" or type(v) == "string" or type(v) == "number" then
            local k_lower = string.lower(k)
            local matched = false
            for _, word in ipairs(keywords) do
                if string.find(k_lower, word) then
                    matched = true
                    break
                end
            end
            if matched then
                table.insert(methods, '"' .. k .. '": "' .. type(v) .. '"')
            end
        end
    end

    status = "DISCOVERY_SUCCESS"

    local f = io.open(out_path, "w")
    if f then
        line(f, "{{")
        line(f, '  "run_id": ' .. esc(run_id) .. ',')
        line(f, '  "executed": true,')
        line(f, '  "status": ' .. esc(status) .. ',')
        line(f, '  "methods": {{')
        for i, m in ipairs(methods) do
            if i < #methods then
                line(f, '    ' .. m .. ',')
            else
                line(f, '    ' .. m)
            end
        end
        line(f, '  }},')
        line(f, '  "error": null')
        line(f, "}}")
        f:close()
    end
end)

if not ok then
    local f = io.open(out_path, "w")
    if f then
        line(f, "{{")
        line(f, '  "run_id": ' .. esc(run_id) .. ',')
        line(f, '  "executed": false,')
        line(f, '  "status": ' .. esc(status) .. ',')
        line(f, '  "error": ' .. esc(tostring(err)))
        line(f, "}}")
        f:close()
    end
end
"""
