--------------------------------------------------------------------------------
-- WARNING: Generated template only. Not hardware validated. Review before use.
-- Generated by awr2944_dca from: C:\Users\khams008\Documents\awr2944-fmcw-radar\examples\configs\first_capture.yaml
--
-- This file is a TEMPLATE based on our capture.yaml config.
-- Parameter positions in ar1.*() calls are based on reverse-engineering
-- DataCaptureDemo_xWR.lua and may not be correct for all firmware versions.
--
-- DO NOT run this on hardware without reviewing every parameter.
--------------------------------------------------------------------------------


-- ADC data output path
-- TODO: Update this path to your actual capture directory
adc_data_path = "C:\\ti\\mmwave_studio\\PostProc\\adc_data.bin"

-- TODO: Download BSS and MSS firmware (device-specific)
-- ar1.DownloadBSSFw(BSS_FW)
-- ar1.DownloadMSSFw(MSS_FW)
-- RSTD.Sleep(100)

-- TODO: Power on and RF enable
-- ar1.PowerOn(1, 1000, 0, 0)
-- ar1.RfEnable()
-- RSTD.Sleep(100)

-- Channel and ADC Configuration
-- TX enable mask: 1 ([0])
-- RX enable mask: 15 ([0, 1, 2, 3])
-- ADC bits enum: 2 (16-bit)
-- ADC format: 0 (real)
-- IQ swap: 0
-- Channel interleave: 1
ar1.ChanNAdcConfig(1, 15, 0, 2, 0, 0, 1, 2, 1, 0)
RSTD.Sleep(100)

-- Low Power Mode (regular mode)
ar1.LPModConfig(0, 0)
RSTD.Sleep(100)

-- RF Init
ar1.RfInit()
RSTD.Sleep(1000)

-- Data Path Configuration
-- TODO: Verify intfSel parameter for your device
ar1.DataPathConfig(1, 1, 0)
RSTD.Sleep(100)

-- LVDS Clock Configuration
ar1.LvdsClkConfig(1, 1)
RSTD.Sleep(100)

-- LVDS Lane Configuration
-- TODO: Verify lane enable mask for AWR2944 (2-lane)
ar1.LVDSLaneConfig(0, 1, 1, 1, 1, 1, 0, 0)
RSTD.Sleep(100)

-- Profile Configuration
-- Start freq: 77.0 GHz
-- Idle time: 10.0 us
-- Ramp end time: 60.0 us
-- Slope: 60.0 MHz/us
-- Samples: 256
-- Sample rate: 10000.0 ksps
ar1.ProfileConfig(0, 77.0, 10.0, 6, 60.0, 0, 0, 0, 0, 0, 0, 60.0, 0, 256, 10000.0, 0, 0, 94)
RSTD.Sleep(100)

-- Chirp Configuration
-- TODO: Verify chirp parameters for your setup
ar1.ChirpConfig(0, 0, 0, 0, 0, 0, 0, 1, 1, 0)
RSTD.Sleep(100)

-- Frame Configuration
-- Chirps per frame: 128
-- Num frames: 10
-- Frame period: 50.0 ms
-- TODO: Verify framePeriodicity units (may need conversion)
ar1.FrameConfig(0, 0, 128, 10, 50.0, 0, 1)
RSTD.Sleep(100)

-- DCA1000 Capture Card Setup
ar1.SelectCaptureDevice("DCA1000")
ar1.CaptureCardConfig_EthInit("192.168.33.30", "192.168.33.180", "12:34:56:78:90:12", 4096, 4098)
ar1.CaptureCardConfig_Mode(1, 1, 1, 2, 3, 30)
ar1.CaptureCardConfig_PacketDelay(25)

-- Start Capture
ar1.CaptureCardConfig_StartRecord(adc_data_path, 1)
RSTD.Sleep(2000)

-- Trigger Frame
ar1.StartFrame()
RSTD.Sleep(5000)

-- Post Processing
ar1.StartMatlabPostProc(adc_data_path)
WriteToLog("Capture complete. Run post-processing.\n", "green")
RSTD.Sleep(10000)
